package(default_visibility = [
    "//reality/engine:__subpackages__",
])

filegroup(
    name = "roi",
    testonly = 1,
    srcs = [
        "roi.jpg",
    ],
)

filegroup(
    name = "ears-fidelity",
    testonly = 1,
    srcs = [
        "fidelity_testing_cropping.json",
        "fidelity_testing_lifting3d.json",
    ],
)
