load("//bzl/js:js.bzl", "js_library")

package(default_visibility = ["//reality/cloud:shared"])

js_library(
    name = "time-utils",
    srcs = [
        "time-utils.ts",
    ],
)

js_library(
    name = "registry",
    srcs = [
        "registry.ts",
    ],
)

js_library(
    name = "user-editor-settings",
    srcs = [
        "user-editor-settings.ts",
    ],
)

js_library(
    name = "special-features",
    srcs = [
        "special-features.ts",
    ],
)

js_library(
    name = "tos",
    srcs = [
        "tos.ts",
    ],
)
