// Generated by ts-to-zod
import {z} from 'zod'

const alignContentSchema = z.union([z.literal('flex-start'), z.literal('flex-end'), z.literal('center'), z.literal('stretch'), z.literal('space-between'), z.literal('space-around'), z.literal('space-evenly')])

const alignItemsSchema = z.union([z.literal('flex-start'), z.literal('flex-end'), z.literal('center'), z.literal('stretch'), z.literal('baseline')])

const justifyContentSchema = z.union([z.literal('flex-start'), z.literal('flex-end'), z.literal('center'), z.literal('space-between'), z.literal('space-around'), z.literal('space-evenly')])

const textAlignContentSchema = z.union([z.literal('left'), z.literal('center'), z.literal('right'), z.literal('justify')])

const verticalTextAlignContentSchema = z.union([z.literal('start'), z.literal('center'), z.literal('end')])

const flexWrapSchema = z.union([z.literal('nowrap'), z.literal('wrap'), z.literal('wrap-reverse')])

const flexDirectionSchema = z.union([z.literal('row'), z.literal('column'), z.literal('row-reverse'), z.literal('column-reverse')])

const directionSchema = z.union([z.literal('ltr'), z.literal('rtl')])

const displaySchema = z.union([z.literal('none'), z.literal('flex')])

const overflowSchema = z.union([z.literal('visible'), z.literal('hidden'), z.literal('scroll')])

const positionModeSchema = z.union([z.literal('absolute'), z.literal('relative'), z.literal('static')])

export {
  alignContentSchema,
  alignItemsSchema,
  justifyContentSchema,
  textAlignContentSchema,
  verticalTextAlignContentSchema,
  flexWrapSchema,
  flexDirectionSchema,
  directionSchema,
  displaySchema,
  overflowSchema,
  positionModeSchema,
}
