// Generated by ts-to-zod
import {z} from 'zod'

import * as FlexStyles from './flex-style-types'

const vec2TupleSchema = z.array(z.number()).length(2).describe('A 2D vector represented by [x, y] coordinates. Can represent a point in a plane, a directional vector, or other 2D quantities.')

const vec3TupleSchema = z.array(z.number()).length(3).describe('A 3D vector represented by [x, y, z] coordinates. Can represent a point in space, a directional vector, or other 3D quantities.')

const vec4TupleSchema = z.array(z.number()).length(4).describe('A 4D vector represented by [x, y, z, w] coordinates. Often used for homogeneous coordinates in 3D transformations or for quaternions.')

const vec6TupleSchema = z.array(z.number()).length(6).describe('Used to represent shadow camera frustum bounds: left, right, top, bottom, near, far.')

const objectIdSchema = z.string().describe('An object ID.')
const entityReferenceSchema = z.object({
  type: z.literal('entity'),
  id: objectIdSchema,
})

const boxGeometrySchema = z.object({
  type: z.literal('box'),
  width: z.number(),
  height: z.number(),
  depth: z.number(),
})

const sphereGeometrySchema = z.object({
  type: z.literal('sphere'),
  radius: z.number(),
})

const planeGeometrySchema = z.object({
  type: z.literal('plane'),
  width: z.number(),
  height: z.number(),
})

const capsuleGeometrySchema = z.object({
  type: z.literal('capsule'),
  radius: z.number(),
  height: z.number(),
})

const coneGeometrySchema = z.object({
  type: z.literal('cone'),
  radius: z.number(),
  height: z.number(),
})

const cylinderGeometrySchema = z.object({
  type: z.literal('cylinder'),
  radius: z.number(),
  height: z.number(),
})

const tetrahedronGeometrySchema = z.object({
  type: z.literal('tetrahedron'),
  radius: z.number(),
})

const facesSchema = z.union([z.literal(4), z.literal(8), z.literal(12), z.literal(20)])

const polyhedronGeometrySchema = z.object({
  type: z.literal('polyhedron'),
  radius: z.number(),
  faces: facesSchema,
})

const circleGeometrySchema = z.object({
  type: z.literal('circle'),
  radius: z.number(),
})

const ringGeometrySchema = z.object({
  type: z.literal('ring'),
  innerRadius: z.number(),
  outerRadius: z.number(),
})

const torusGeometrySchema = z.object({
  type: z.literal('torus'),
  radius: z.number(),
  tubeRadius: z.number(),
})

const faceGeometrySchema = z.object({
  type: z.literal('face'),
  id: z.number(),
})

const sideSchema = z.union([z.literal('front'), z.literal('back'), z.literal('double')])

const materialBlendingSchema = z.union([z.literal('no'), z.literal('normal'), z.literal('additive'), z.literal('subtractive'), z.literal('multiply')])

const textureWrapSchema = z.union([z.literal('clamp'), z.literal('repeat'), z.literal('mirroredRepeat')])

const hiderMaterialSchema = z.object({
  type: z.literal('hider'),
})

const shadowMaterialSchema = z.object({
  type: z.literal('shadow'),
  color: z.string(),
  opacity: z.number().optional(),
  side: sideSchema.optional(),
  depthTest: z.boolean().optional(),
  depthWrite: z.boolean().optional(),
})

const geometrySchema = z.union([boxGeometrySchema, sphereGeometrySchema, planeGeometrySchema, capsuleGeometrySchema, coneGeometrySchema, cylinderGeometrySchema, tetrahedronGeometrySchema, polyhedronGeometrySchema, circleGeometrySchema, ringGeometrySchema, torusGeometrySchema, faceGeometrySchema]).nullable()

const geometryTypeSchema = z.union([z.literal('box'), z.literal('sphere'), z.literal('plane'), z.literal('capsule'), z.literal('cone'), z.literal('cylinder'), z.literal('tetrahedron'), z.literal('polyhedron'), z.literal('circle'), z.literal('ring'), z.literal('torus'), z.literal('face')])

const urlSchema = z.object({
  type: z.literal('url'),
  url: z.string(),
})

const assetSchema = z.object({
  type: z.literal('asset'),
  asset: z.string(),
})

const resourceSchema = z.union([urlSchema, assetSchema])

const gltfModelSchema = z.object({
  src: resourceSchema,
  animationClip: z.string().optional(),
  loop: z.boolean().optional(),
  paused: z.boolean().optional(),
  timeScale: z.number().optional(),
  reverse: z.boolean().optional(),
  repetitions: z.number().optional(),
  crossFadeDuration: z.number().optional(),
})

const splatSchema = z.object({
  src: resourceSchema,
  skybox: z.boolean().optional(),
})

const colliderTypeSchema = z.union([z.literal('box'), z.literal('sphere'), z.literal('plane'), z.literal('capsule'), z.literal('cone'), z.literal('cylinder'), z.literal('auto')])

const colliderSchema = z.object({
  geometry: z.union([boxGeometrySchema, sphereGeometrySchema, planeGeometrySchema, capsuleGeometrySchema, coneGeometrySchema, cylinderGeometrySchema, z.object({
    type: z.literal('auto'),
  })]).optional(),
  mass: z.number().optional(),
  linearDamping: z.number().optional(),
  angularDamping: z.number().optional(),
  friction: z.number().optional(),
  rollingFriction: z.number().optional(),
  spinningFriction: z.number().optional(),
  restitution: z.number().optional(),
  eventOnly: z.boolean().optional(),
  lockXPosition: z.boolean().optional(),
  lockYPosition: z.boolean().optional(),
  lockZPosition: z.boolean().optional(),
  lockXAxis: z.boolean().optional(),
  lockYAxis: z.boolean().optional(),
  lockZAxis: z.boolean().optional(),
  gravityFactor: z.number().optional(),
})

const fontResourceSchema = z.union([z.object({
  type: z.literal('font'),
  font: z.string(),
}), resourceSchema])

const uiRootTypeSchema = z.union([z.literal('overlay'), z.literal('3d')])

const backgroundSizeSchema = z.union([z.literal('contain'), z.literal('cover'), z.literal('stretch'), z.literal('nineslice')])

const uiGraphSettingsSchema = z.object({
  top: z.string(),
  left: z.string(),
  right: z.string(),
  bottom: z.string(),
  width: z.union([z.number(), z.string()]),
  height: z.union([z.number(), z.string()]),
  type: uiRootTypeSchema,
  font: fontResourceSchema,
  background: z.string(),
  backgroundOpacity: z.number(),
  backgroundSize: backgroundSizeSchema,
  nineSliceBorderTop: z.string(),
  nineSliceBorderBottom: z.string(),
  nineSliceBorderLeft: z.string(),
  nineSliceBorderRight: z.string(),
  nineSliceScaleFactor: z.number(),
  opacity: z.number(),
  color: z.string(),
  text: z.string(),
  textAlign: FlexStyles.textAlignContentSchema,
  verticalTextAlign: FlexStyles.verticalTextAlignContentSchema,
  image: resourceSchema,
  fixedSize: z.boolean(),
  borderColor: z.string(),
  borderRadius: z.number(),
  borderRadiusTopLeft: z.string(),
  borderRadiusTopRight: z.string(),
  borderRadiusBottomRight: z.string(),
  borderRadiusBottomLeft: z.string(),
  fontSize: z.number(),
  alignContent: FlexStyles.alignContentSchema,
  alignItems: FlexStyles.alignItemsSchema,
  alignSelf: FlexStyles.alignItemsSchema,
  borderWidth: z.number(),
  direction: FlexStyles.directionSchema,
  display: FlexStyles.displaySchema,
  flex: z.number(),
  flexBasis: z.string(),
  flexDirection: FlexStyles.flexDirectionSchema,
  rowGap: z.string(),
  gap: z.string(),
  columnGap: z.string(),
  flexGrow: z.number(),
  flexShrink: z.number(),
  flexWrap: FlexStyles.flexWrapSchema,
  justifyContent: FlexStyles.justifyContentSchema,
  margin: z.string(),
  marginBottom: z.string(),
  marginLeft: z.string(),
  marginRight: z.string(),
  marginTop: z.string(),
  maxHeight: z.string(),
  maxWidth: z.string(),
  minHeight: z.string(),
  minWidth: z.string(),
  overflow: FlexStyles.overflowSchema,
  padding: z.string(),
  paddingBottom: z.string(),
  paddingLeft: z.string(),
  paddingRight: z.string(),
  paddingTop: z.string(),
  position: FlexStyles.positionModeSchema,
  video: resourceSchema,
}).partial()

const shadowSchema = z.object({
  castShadow: z.boolean().optional(),
  receiveShadow: z.boolean().optional(),
})

const distanceModelSchema = z.union([z.literal('exponential'), z.literal('inverse'), z.literal('linear')])

const audioSettingsSchema = z.object({
  src: resourceSchema,
  volume: z.number().optional(),
  loop: z.boolean().optional(),
  paused: z.boolean().optional(),
  pitch: z.number().optional(),
  positional: z.boolean().optional(),
  refDistance: z.number().optional(),
  rolloffFactor: z.number().optional(),
  distanceModel: distanceModelSchema.optional(),
  maxDistance: z.number().optional(),
})

const lightTypeSchema = z.union([z.literal('directional'), z.literal('ambient'), z.literal('point'), z.literal('spot')])

const lightSchema = z.object({
  type: lightTypeSchema,
  color: z.string().optional(),
  intensity: z.number().optional(),
  castShadow: z.boolean().optional(),
  target: vec3TupleSchema.optional(),
  shadowNormalBias: z.number().optional(),
  shadowBias: z.number().optional(),
  shadowAutoUpdate: z.boolean().optional(),
  shadowBlurSamples: z.number().optional(),
  shadowRadius: z.number().optional(),
  shadowMapSize: vec2TupleSchema.optional(),
  shadowCamera: vec6TupleSchema.optional(),
  distance: z.number().optional(),
  decay: z.number().optional(),
  followCamera: z.boolean().optional(),
  angle: z.number().optional(),
  penumbra: z.number().optional(),
  colorMap: resourceSchema.optional(),
})

const cameraTypeSchema = z.union([z.literal('perspective'), z.literal('orthographic')])

const xrCameraTypeSchema = z.union([z.literal('world'), z.literal('face'), z.literal('hand'), z.literal('layers'), z.literal('worldLayers'), z.literal('3dOnly')])

const deviceSupportTypeSchema = z.union([z.literal('AR'), z.literal('VR'), z.literal('3D'), z.literal('disabled')])

const cameraDirectionTypeSchema = z.union([z.literal('front'), z.literal('back')])

const xrWorldConfigSchema = z.object({
  scale: z.union([z.literal('absolute'), z.literal('responsive')]).optional(),
  disableWorldTracking: z.boolean().optional(),
  enableLighting: z.boolean().optional(),
  enableWorldPoints: z.boolean().optional(),
  enableVps: z.boolean().optional(),
})

const xrFaceConfigSchema = z.object({
  mirroredDisplay: z.boolean().optional(),
  meshGeometryFace: z.boolean().optional(),
  meshGeometryEyes: z.boolean().optional(),
  meshGeometryIris: z.boolean().optional(),
  meshGeometryMouth: z.boolean().optional(),
  enableEars: z.boolean().optional(),
  maxDetections: z.number().optional(),
})

const faceSchema = z.object({
  id: z.number(),
  addAttachmentState: z.boolean(),
})

const imageTargetSchema = z.object({
  name: z.string(),
})

const locationVisualizationSchema = z.union([z.literal('mesh'), z.literal('splat'), z.literal('none')])

const locationSchema = z.object({
  name: z.string(),
  poiId: z.string(),
  lat: z.number(),
  lng: z.number(),
  title: z.string(),
  anchorNodeId: z.string(),
  anchorSpaceId: z.string(),
  imageUrl: z.string(),
  anchorPayload: z.string(),
  visualization: locationVisualizationSchema.optional(),
})

const mapSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  targetEntity: entityReferenceSchema.optional(),
  radius: z.number(),
  spawnLocations: z.boolean(),
  useGps: z.boolean(),
})

const mapThemeSchema = z.object({
  landColor: z.string().optional(),
  buildingColor: z.string().optional(),
  parkColor: z.string().optional(),
  parkingColor: z.string().optional(),
  roadColor: z.string().optional(),
  sandColor: z.string().optional(),
  transitColor: z.string().optional(),
  waterColor: z.string().optional(),
  landOpacity: z.number().optional(),
  buildingOpacity: z.number().optional(),
  parkOpacity: z.number().optional(),
  parkingOpacity: z.number().optional(),
  roadOpacity: z.number().optional(),
  sandOpacity: z.number().optional(),
  transitOpacity: z.number().optional(),
  waterOpacity: z.number().optional(),
  lod: z.number().optional(),
  buildingBase: z.number().optional(),
  parkBase: z.number().optional(),
  parkingBase: z.number().optional(),
  roadBase: z.number().optional(),
  sandBase: z.number().optional(),
  transitBase: z.number().optional(),
  waterBase: z.number().optional(),
  buildingMinMeters: z.number().optional(),
  buildingMaxMeters: z.number().optional(),
  roadLMeters: z.number().optional(),
  roadMMeters: z.number().optional(),
  roadSMeters: z.number().optional(),
  roadXLMeters: z.number().optional(),
  transitMeters: z.number().optional(),
  waterMeters: z.number().optional(),
  roadLMin: z.number().optional(),
  roadMMin: z.number().optional(),
  roadSMin: z.number().optional(),
  roadXLMin: z.number().optional(),
  transitMin: z.number().optional(),
  waterMin: z.number().optional(),
  landVisibility: z.boolean().optional(),
  buildingVisibility: z.boolean().optional(),
  parkVisibility: z.boolean().optional(),
  parkingVisibility: z.boolean().optional(),
  roadVisibility: z.boolean().optional(),
  sandVisibility: z.boolean().optional(),
  transitVisibility: z.boolean().optional(),
  waterVisibility: z.boolean().optional(),
})

const mapPointSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  targetEntity: entityReferenceSchema.optional(),
  meters: z.number(),
  minScale: z.number(),
})

const graphComponentSchema = z.object({
  id: objectIdSchema,
  name: z.string(),
  parameters: z.record(z.union([z.string(), z.number(), z.boolean(), entityReferenceSchema])),
})

const prefabInstanceDeletionsSchema = z.record(z.string(), z.literal(true))

const bindingSchema = z.object({
  input: z.string(),
  modifiers: z.array(z.string()),
})

const actionSchema = z.object({
  name: z.string(),
  bindings: z.array(bindingSchema),
})

const inputMapSchema = z.record(z.array(actionSchema))

const colorSchema = z.object({
  type: z.literal('color'),
  color: z.string().optional(),
})

const gradientStyleSchema = z.union([z.literal('linear'), z.literal('radial')])

const gradientSchema = z.object({
  type: z.literal('gradient'),
  style: gradientStyleSchema.optional(),
  colors: z.array(z.string()).optional(),
})

const imageSchema = z.object({
  type: z.literal('image'),
  src: resourceSchema.optional(),
})

const noSkySchema = z.object({
  type: z.literal('none'),
})

const skySchema = z.union([colorSchema, gradientSchema, imageSchema, noSkySchema])

const unlitMaterialSchema = z.object({
  type: z.literal('unlit'),
  color: z.string(),
  textureSrc: z.union([z.string(), resourceSchema]).optional(),
  opacity: z.number().optional(),
  opacityMap: z.union([z.string(), resourceSchema]).optional(),
  side: sideSchema.optional(),
  blending: materialBlendingSchema.optional(),
  repeatX: z.number().optional(),
  repeatY: z.number().optional(),
  offsetX: z.number().optional(),
  offsetY: z.number().optional(),
  wrap: textureWrapSchema.optional(),
  depthTest: z.boolean().optional(),
  depthWrite: z.boolean().optional(),
  wireframe: z.boolean().optional(),
  forceTransparent: z.boolean().optional(),
})

const basicMaterialSchema = z.object({
  type: z.literal('basic'),
  color: z.string(),
  textureSrc: z.union([z.string(), resourceSchema]).optional(),
  roughness: z.number().optional(),
  metalness: z.number().optional(),
  opacity: z.number().optional(),
  normalScale: z.number().optional(),
  emissiveIntensity: z.number().optional(),
  roughnessMap: z.union([z.string(), resourceSchema]).optional(),
  metalnessMap: z.union([z.string(), resourceSchema]).optional(),
  opacityMap: z.union([z.string(), resourceSchema]).optional(),
  normalMap: z.union([z.string(), resourceSchema]).optional(),
  emissiveMap: z.union([z.string(), resourceSchema]).optional(),
  emissiveColor: z.string().optional(),
  side: sideSchema.optional(),
  blending: materialBlendingSchema.optional(),
  repeatX: z.number().optional(),
  repeatY: z.number().optional(),
  offsetX: z.number().optional(),
  offsetY: z.number().optional(),
  wrap: textureWrapSchema.optional(),
  depthTest: z.boolean().optional(),
  depthWrite: z.boolean().optional(),
  wireframe: z.boolean().optional(),
  forceTransparent: z.boolean().optional(),
})

const materialSchema = z.union([basicMaterialSchema, unlitMaterialSchema, shadowMaterialSchema, hiderMaterialSchema]).nullable()

const xrConfigSchema = z.object({
  xrCameraType: xrCameraTypeSchema.optional(),
  phone: deviceSupportTypeSchema.optional(),
  desktop: deviceSupportTypeSchema.optional(),
  headset: deviceSupportTypeSchema.optional(),
  leftHandedAxes: z.boolean().optional(),
  uvType: z.union([z.literal('standard'), z.literal('projected')]).optional(),
  direction: cameraDirectionTypeSchema.optional(),
  world: xrWorldConfigSchema.optional(),
  face: xrFaceConfigSchema.optional(),
})

const cameraSchema = z.object({
  type: cameraTypeSchema.optional(),
  left: z.number().optional(),
  right: z.number().optional(),
  top: z.number().optional(),
  bottom: z.number().optional(),
  fov: z.number().optional(),
  zoom: z.number().optional(),
  nearClip: z.number().optional(),
  farClip: z.number().optional(),
  xr: xrConfigSchema.optional(),
})

const baseGraphObjectSchema = z.object({
  id: objectIdSchema,
  name: z.string().optional(),
  parentId: z.string().optional(),
  prefab: z.literal(true).optional(),
  position: vec3TupleSchema,
  rotation: vec4TupleSchema,
  scale: vec3TupleSchema,
  geometry: geometrySchema,
  material: materialSchema,
  gltfModel: z.union([gltfModelSchema, z.undefined()]).optional().nullable(),
  splat: z.union([splatSchema, z.undefined()]).optional().nullable(),
  collider: z.union([colliderSchema, z.undefined()]).optional().nullable(),
  audio: z.union([audioSettingsSchema, z.undefined()]).optional().nullable(),
  ui: z.union([uiGraphSettingsSchema, z.undefined()]).optional().nullable(),
  hidden: z.boolean().optional(),
  shadow: shadowSchema.optional(),
  light: lightSchema.optional(),
  camera: cameraSchema.optional(),
  face: faceSchema.optional(),
  imageTarget: imageTargetSchema.optional(),
  location: locationSchema.optional(),
  map: mapSchema.optional(),
  mapTheme: mapThemeSchema.optional(),
  mapPoint: mapPointSchema.optional(),
  components: z.record(graphComponentSchema.shape.id, graphComponentSchema),
  ephemeral: z.boolean().optional(),
  disabled: z.literal(true).optional(),
  persistent: z.literal(true).optional(),
  order: z.number().optional(),
})

const prefabInstanceChildrenDataSchema = baseGraphObjectSchema.partial().omit({'id': true, 'prefab': true}).and(z.object({
  id: z.string().optional(),
  deletions: prefabInstanceDeletionsSchema.optional(),
  deleted: z.literal(true).optional(),
}))

const prefabInstanceChildrenSchema = z.record(prefabInstanceChildrenDataSchema)

const instanceDataSchema = z.object({
  instanceOf: z.string(),
  deletions: prefabInstanceDeletionsSchema,
  children: prefabInstanceChildrenSchema.optional(),
})

const spaceSchema = z.object({
  id: z.string(),
  name: z.string(),
  sky: skySchema.optional(),
  activeCamera: z.string().optional(),
  includedSpaces: z.array(z.string()).optional(),
  reflections: z.union([z.string(), resourceSchema]).optional().nullable(),
})

const spacesSchema = z.record(spaceSchema)

const graphObjectSchema = baseGraphObjectSchema.partial().and(z.object({
  id: objectIdSchema,
  components: z.record(graphComponentSchema.shape.id, graphComponentSchema),
  instanceData: instanceDataSchema.optional(),
}))

const sceneGraphSchema = z.object({
  activeCamera: z.string().optional(),
  activeMap: z.string().optional(),
  inputs: inputMapSchema.optional(),
  sky: skySchema.optional(),
  reflections: z.union([z.string(), resourceSchema]).optional(),
  entrySpaceId: z.string().optional(),
  spaces: spacesSchema.optional(),
  objects: z.record(graphObjectSchema),
})

const expanseSchema = sceneGraphSchema.and(z.object({
  history: z.string().optional(),
  historyVersion: z.string().optional(),
}))

export {
  vec2TupleSchema,
  vec3TupleSchema,
  vec4TupleSchema,
  vec6TupleSchema,
  objectIdSchema,
  entityReferenceSchema,
  boxGeometrySchema,
  sphereGeometrySchema,
  planeGeometrySchema,
  capsuleGeometrySchema,
  coneGeometrySchema,
  cylinderGeometrySchema,
  tetrahedronGeometrySchema,
  facesSchema,
  polyhedronGeometrySchema,
  circleGeometrySchema,
  ringGeometrySchema,
  torusGeometrySchema,
  faceGeometrySchema,
  sideSchema,
  materialBlendingSchema,
  textureWrapSchema,
  hiderMaterialSchema,
  shadowMaterialSchema,
  geometrySchema,
  geometryTypeSchema,
  urlSchema,
  assetSchema,
  resourceSchema,
  gltfModelSchema,
  splatSchema,
  colliderTypeSchema,
  colliderSchema,
  fontResourceSchema,
  uiRootTypeSchema,
  backgroundSizeSchema,
  uiGraphSettingsSchema,
  shadowSchema,
  distanceModelSchema,
  audioSettingsSchema,
  lightTypeSchema,
  lightSchema,
  cameraTypeSchema,
  xrCameraTypeSchema,
  deviceSupportTypeSchema,
  cameraDirectionTypeSchema,
  xrWorldConfigSchema,
  xrFaceConfigSchema,
  faceSchema,
  imageTargetSchema,
  locationVisualizationSchema,
  locationSchema,
  mapSchema,
  mapThemeSchema,
  mapPointSchema,
  graphComponentSchema,
  prefabInstanceDeletionsSchema,
  bindingSchema,
  actionSchema,
  inputMapSchema,
  colorSchema,
  gradientStyleSchema,
  gradientSchema,
  imageSchema,
  noSkySchema,
  skySchema,
  unlitMaterialSchema,
  basicMaterialSchema,
  materialSchema,
  xrConfigSchema,
  cameraSchema,
  baseGraphObjectSchema,
  prefabInstanceChildrenDataSchema,
  prefabInstanceChildrenSchema,
  instanceDataSchema,
  spaceSchema,
  spacesSchema,
  graphObjectSchema,
  sceneGraphSchema,
  expanseSchema,
}
