package(default_visibility = ["//visibility:public"])


filegroup(
    name = "mock-mesh-data",
    srcs = [
        "mock-mesh-data.json",
    ],
)

filegroup(
    name = "splat-asset",
    srcs = [
        "doty-platformer.spz",
    ],
)
