load("//bzl/js:js.bzl", "js_library")

package(default_visibility = [
    "//apps/desktop:__subpackages__",
])

js_library(
    name = "dev8-socket-server",
    srcs = [
        "dev8-socket-server.ts",
    ],
)
