const events = {
  ACTIVE_SPACE_CHANGE: 'active-space-change',
  AUDIO_CAN_PLAY_THROUGH: 'audio-can-play-through',
  AUDIO_END: 'audio-end',
  VIDEO_CAN_PLAY_THROUGH: 'video-can-play-through',
  VIDEO_END: 'video-end',
  GLTF_MODEL_LOADED: 'gltf-model-loaded',
  GLTF_ANIMATION_FINISHED: 'gltf-animation-finished',
  GLTF_ANIMATION_LOOP: 'gltf-animation-loop',
  SPLAT_MODEL_LOADED: 'splat-model-loaded',
  POSITION_ANIMATION_COMPLETE: 'position-animation-complete',
  SCALE_ANIMATION_COMPLETE: 'scale-animation-complete',
  ROTATE_ANIMATION_COMPLETE: 'rotate-animation-complete',
  CUSTOM_VEC3_ANIMATION_COMPLETE: 'vector3-animation-complete',
  CUSTOM_PROPERTY_ANIMATION_COMPLETE: 'animation-complete',
  LOCATION_SPAWNED: 'locationSpawned',
  RECORDER_VIDEO_STARTED: 'recorder-video-started',
  RECORDER_VIDEO_STOPPED: 'recorder-video-stopped',
  RECORDER_VIDEO_ERROR: 'recorder-video-error',
  RECORDER_VIDEO_READY: 'recorder-video-ready',
  RECORDER_FINALIZE_PROGRESS: 'recorder-finalize-progress',
  RECORDER_PREVIEW_READY: 'recorder-preview-ready',
  RECORDER_PROCESS_FRAME: 'recorder-process-frame',
  RECORDER_SCREENSHOT_READY: 'recorder-screenshot-ready',

  // engine events
  REALITY_CAMERA_CONFIGURED: 'reality.cameraconfigured',
  REALITY_TRACKING_STATUS: 'reality.trackingstatus',
  REALITY_LOCATION_SCANNING: 'reality.locationscanning',
  REALITY_LOCATION_FOUND: 'reality.locationfound',
  REALITY_LOCATION_UPDATED: 'reality.locationupdated',
  REALITY_LOCATION_LOST: 'reality.locationlost',
  REALITY_MESH_FOUND: 'reality.meshfound',
  REALITY_MESH_LOST: 'reality.meshlost',
  REALITY_IMAGE_LOADING: 'reality.imageloading',
  REALITY_IMAGE_SCANNING: 'reality.imagescanning',
  REALITY_IMAGE_FOUND: 'reality.imagefound',
  REALITY_IMAGE_UPDATED: 'reality.imageupdated',
  REALITY_IMAGE_LOST: 'reality.imagelost',
  REALITY_READY: 'realityready',

  FACE_CAMERA_CONFIGURED: 'facecontroller.cameraconfigured',
  FACE_LOADING: 'facecontroller.faceloading',
  FACE_SCANNING: 'facecontroller.facescanning',
  FACE_FOUND: 'facecontroller.facefound',
  FACE_UPDATED: 'facecontroller.faceupdated',
  FACE_LOST: 'facecontroller.facelost',
  FACE_MOUTH_OPENED: 'facecontroller.mouthopened',
  FACE_MOUTH_CLOSED: 'facecontroller.mouthclosed',
  FACE_LEFT_EYE_OPENED: 'facecontroller.lefteyeopened',
  FACE_LEFT_EYE_CLOSED: 'facecontroller.lefteyeclosed',
  FACE_RIGHT_EYE_OPENED: 'facecontroller.righteyeopened',
  FACE_RIGHT_EYE_CLOSED: 'facecontroller.righteyeclosed',
  FACE_LEFT_EYEBROW_RAISED: 'facecontroller.lefteyebrowraised',
  FACE_LEFT_EYEBROW_LOWERED: 'facecontroller.lefteyebrowlowered',
  FACE_RIGHT_EYEBROW_RAISED: 'facecontroller.righteyebrowraised',
  FACE_RIGHT_EYEBROW_LOWERED: 'facecontroller.righteyebrowlowered',
  FACE_RIGHT_EYE_WINKED: 'facecontroller.righteyewinked',
  FACE_LEFT_EYE_WINKED: 'facecontroller.lefteyewinked',
  FACE_BLINKED: 'facecontroller.blinked',
  FACE_INTERPUPILLARY_DISTANCE: 'facecontroller.interpupillarydistance',
  FACE_EAR_POINT_FOUND: 'facecontroller.earpointfound',
  FACE_EAR_POINT_LOST: 'facecontroller.earpointlost',

  HAND_CAMERA_CONFIGURED: 'handcontroller.cameraconfigured',

  LAYERS_CAMERA_CONFIGURED: 'layerscontroller.cameraconfigured',
} as const

export {events}
