package(default_visibility = ["//visibility:public"])

filegroup(
    name = "doty-glb",
    srcs = [
        "doty.glb",
    ],
)

filegroup(
    name = "drc-texture-jpg",
    srcs = [
        "drc-texture.jpg",
    ],
)

filegroup(
    name = "mar-texture-jpg",
    srcs = [
        "mar-texture.jpg",
    ],
)

filegroup(
    name = "mesh-drc",
    srcs = [
        "mesh.drc",
    ],
)

filegroup(
    name = "mesh-mar",
    srcs = [
        "mesh.mar",
    ],
)

filegroup(
    name = "minion-spz",
    srcs = [
        "minion.spz",
    ],
)

filegroup(
    name = "pointcloud-ptz",
    srcs = [
        "pointcloud.ptz",
    ],
)

filegroup(
    name = "sundial-spz",
    srcs = [
        "sundial.spz",
    ],
)

filegroup(
    name = "fixed-number-mural-splats",
    srcs = [
        "mural-splat-100.spz",
        "mural-splat-300.spz",
        "mural-splat-4000.spz",
        "mural-splat-500.spz",
        "mural-splat-700.spz",
        "mural-splat-900.spz",
    ],
)
