import {promises as fs} from 'fs'

import {parseComponentAst} from '../src/shared/ecs/shared/parse-component-ast'

const FILES_TO_INCLUDE = [
  'src/shared/ecs/runtime/animation.ts',
  'src/shared/ecs/runtime/particles.ts',
  'src/shared/ecs/runtime/orbit-controls.ts',
  'src/shared/ecs/runtime/xr/xr-face-components.ts',
  'src/shared/ecs/runtime/fly-controller.ts',
]

const run = async () => {
  const files = await Promise.all(FILES_TO_INCLUDE.map(file => fs.readFile(file, 'utf8')))
  const asts = files.flatMap((file) => {
    const {componentData, errors} = parseComponentAst(file)
    if (errors.length) {
      throw new Error(errors.map(error => error.message).join('\n'))
    }
    return componentData.map(
      (data) => {
        delete data.location
        return data
      }
    )
  })

  // eslint-disable-next-line no-console
  console.log(`\
/* eslint-disable */
// Generated by xrhome/tools/generate-studio-schema.ts
import { DeepReadonly } from 'ts-essentials'
import type {StudioComponentData} from '@ecs/shared/studio-component'

const BUILTIN_COMPONENT_SCHEMA: DeepReadonly<StudioComponentData[]> = ${
  JSON.stringify(asts, null, 2)
}
export {
  BUILTIN_COMPONENT_SCHEMA,
}
`)
}

run()
