package(default_visibility = ["//visibility:public"])

filegroup(
    name = "frame0",
    srcs = [
        "frame_0.jpg",
        "frame_0_portrait.jpg",
    ],
)

filegroup(
    name = "test-input-landscape",
    srcs = [
        "test-input-landscape.png",
    ],
)

filegroup(
    name = "test-input-portrait",
    srcs = [
        "test-input-portrait.png",
    ],
)

filegroup(
    name = "test-png-color-types",
    srcs = [
        "grayscale_alpha_sample.png",
        "grayscale_sample.png",
        "palette_sample.png",
    ],
)

filegroup(
    name = "test-gif-input",
    srcs = [
        "test-gif-input-landscape.gif",
    ],
)
