package(default_visibility = ["//visibility:public"])

filegroup(
    name = "capnpc-js-plugin",
    srcs = [
        "capnpc-js-plugin.sh",
    ],
    data = [
        "@npm-capnpc-js//:modules",
    ],
)

filegroup(
    name = "capnpc-ts-plugin",
    srcs = [
        "capnpc-ts-plugin.sh",
    ],
    data = [
        "@npm-capnpc-ts//:modules",
    ],
)
