config_setting(
    name = "armv7",
    values = {"cpu": "ios_armv7"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "arm64",
    values = {"cpu": "ios_arm64"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "x86",
    values = {"cpu": "ios_x86"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "x86_64",
    values = {"cpu": "ios_x86_64"},
    visibility = ["//visibility:public"],
)
