load("//bzl/capnproto:capnproto.bzl", "capnp_library")

package(
    default_visibility = [
        "//reality/engine/features:__subpackages__",
        "//reality/quality/training:__subpackages__",
    ],
)

capnp_library(
    name = "descriptors",
    srcs = [
        "descriptors.capnp",
    ],
    deps = [],
)
