package(default_visibility = ["//visibility:public"])

filegroup(
    name = "amity-rotated",
    testonly = 1,
    srcs = [
        "amity_rotated.jpg",
    ],
)

filegroup(
    name = "amity-up",
    testonly = 1,
    srcs = [
        "amity_up.jpg",
    ],
)

filegroup(
    name = "flower-big",
    testonly = 1,
    srcs = [
        "flower-big.jpg",
    ],
)
