load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup")

package(default_visibility = ["//c8/ecs:__subpackages__"])

pkg_filegroup(
    name = "resources",
    srcs = [
        "//c8/ecs/resources/draco",
        "//c8/ecs/resources/fonts",
        "//c8/ecs/resources/splat",
    ],
    prefix = "resources",
)
