load("//bzl/js:js.bzl", "js_library")

package(
    default_visibility = ["//visibility:public"],
)

js_library(
    name = "AlignItems",
    srcs = [
        "AlignItems.ts",
    ],
    deps = [
        "//c8/ecs/src/8mesh/utils/block-layout:ContentDirection",
    ],
)

js_library(
    name = "ContentDirection",
    srcs = [
        "ContentDirection.ts",
    ],
)

js_library(
    name = "JustifyContent",
    srcs = [
        "JustifyContent.ts",
    ],
    deps = [
        "//c8/ecs/src/8mesh/utils/block-layout:ContentDirection",
    ],
)
