// @rule(js_cli)

/* eslint-disable no-console */
import {promises as fs} from 'fs'

import {
  messages,
  WindowObjects,
  Declaration,
  cppTypeToTs,
  findDeclarations,
  findWindowObjects,
  parameterToTs,
} from '@repo/bzl/js/codegen/generate-ts-from-cpp'

const run = async (ccPaths: string[]) => {
  const declarations: Declaration[] = []
  const windowObjects: WindowObjects = {}

  for (let i = 0; i < ccPaths.length; i++) {
    // eslint-disable-next-line no-await-in-loop
    const contents = await fs.readFile(ccPaths[i], 'utf8')
    findDeclarations(contents, declarations)
    findWindowObjects(contents, windowObjects)
  }

  // file header
  console.log(`\
// This file was autogenerated by generate-xrcc-types.ts
//   npm run refresh-types

// @inliner-off
import type {EmscriptenModule} from '@repo/reality/app/xr/js/src/types/emscripten'

/* eslint-disable import/group-exports, camelcase, max-len */
`)

  // Type the module with found methods
  const lines = declarations.map((declaration) => {
    const result = cppTypeToTs(declaration.returnType)
    const parameters = declaration.parameters.map(parameterToTs).join(', ')
    // eslint-disable-next-line no-console
    return (`  _${declaration.functionName}: (${parameters}) => ${result}`)
  })

  console.log('export type XrccModule = EmscriptenModule & {')

  lines.forEach(e => console.log(e))

  console.log('}')

  if (messages.length) {
    console.warn('\n\ngenerate-xrcc-types:')
    messages.forEach(m => console.warn('   ', m))
    console.warn('\n\n')
  }
}

run(process.argv.slice(2))
