// @rule(js_cli)

/* eslint-disable no-console */
import {promises as fs} from 'fs'

import {
  messages,
  Declaration,
  cppTypeToTs,
  findDeclarations,
  parameterToTs,
} from '@repo/bzl/js/codegen/generate-ts-from-cpp'

const run = async (ccPaths: string[]) => {
  const chunkName = process.argv[2]
  const chunkModuleName = `${chunkName}Module`

  const declarations: Declaration[] = []

  for (let i = 0; i < ccPaths.length; i++) {
    // eslint-disable-next-line no-await-in-loop
    const contents = await fs.readFile(ccPaths[i], 'utf8')
    findDeclarations(contents, declarations)
  }

  console.log('// This file was autogenerated by generate-xrchunk-types')
  console.log('//   npm run refresh-types')

  console.log(`\

// @inliner-off
import type {EmscriptenModule} from '@repo/reality/app/xr/js/src/types/emscripten'

/* eslint-disable import/group-exports, camelcase, max-len */
`)

  // Type the module with found methods
  const lines = declarations.map((declaration) => {
    const result = cppTypeToTs(declaration.returnType)
    const parameters = declaration.parameters.map(parameterToTs).join(', ')
    // eslint-disable-next-line no-console
    return (`  _${declaration.functionName}: (${parameters}) => ${result}`)
  })

  console.log('export type', chunkModuleName, '= EmscriptenModule & {')

  lines.forEach(e => console.log(e))

  console.log('}')

  if (messages.length) {
    console.warn('\n\n', chunkName, ':')
    messages.forEach(m => console.warn('   ', m))
    console.warn('\n\n')
  }
}

run(process.argv.slice(3))
