// @rule(js_cli)

/* eslint-disable no-console */
import {promises as fs} from 'fs'

import {
  WindowObjects,
  Declaration,
  findDeclarations,
  findWindowObjects,
} from '@repo/bzl/js/codegen/generate-ts-from-cpp'

const run = async (ccPaths: string[]) => {
  const declarations: Declaration[] = []
  const windowObjects: WindowObjects = {}

  for (let i = 0; i < ccPaths.length; i++) {
    // eslint-disable-next-line no-await-in-loop
    const contents = await fs.readFile(ccPaths[i], 'utf8')
    findDeclarations(contents, declarations)
    findWindowObjects(contents, windowObjects)
  }

  // file header
  console.log(`\
// This file was autogenerated by generate-xrmodule-types.ts
//   npm run refresh-types

// @inliner-off
import type {EmscriptenTexture} from '@repo/reality/app/xr/js/src/types/emscripten'

/* eslint-disable import/group-exports, camelcase, max-len */
`)

  // Define the objects used to send data out of the xrcc module
  console.log(`\
declare global {
  interface Window {`)
  Object.entries(windowObjects).forEach(([objectName, fields]) => {
    console.log(`    ${objectName}: {`)
    Object.entries(fields).forEach(([fieldName, fieldType]) => {
      console.log(`      ${fieldName}?: ${fieldType}`)
    })
    console.log('    }')
  })
  console.log('  }\n}')
}

run(process.argv.slice(2))
