// @rule(js_cli)

/* eslint-disable no-console */

import {promises as fs} from 'fs'

import {
  messages,
  Declaration,
  cppTypeToTs,
  findDeclarations,
  parameterToTs,
} from '@repo/bzl/js/codegen/generate-ts-from-cpp'

const run = async (ccPaths: string[]) => {
  const declarations: Declaration[] = []

  for (let i = 0; i < ccPaths.length; i++) {
    // eslint-disable-next-line no-await-in-loop
    const contents = await fs.readFile(ccPaths[i], 'utf8')
    findDeclarations(contents, declarations)
  }

  // file header
  console.log(`\
// This file was autogenerated by generate-asm-types.ts

/* eslint-disable import/group-exports, camelcase, max-len */
type EmscriptenModule = {
  dataView: DataView
  _malloc: (bytes: number) => number
  _free: (ptr: number) => void
  HEAPU32: Uint32Array
  HEAPU8: Uint8Array
  HEAPU328: Uint8Array
  HEAPF32: Float32Array
  HEAPF64: Float64Array
  HEAPF16: Float32Array
  HEAPU16: Uint16Array
  HEAPU64: BigUint64Array
}
`)

  // Type the module with found methods
  const lines = declarations.map((declaration) => {
    const result = cppTypeToTs(declaration.returnType)
    const parameters = declaration.parameters.map(parameterToTs).join(', ')
    // eslint-disable-next-line no-console
    return (`  ${declaration.functionName.replace('c8EmAsm_', '')}: (${parameters}) => ${result}`)
  })

  if (messages.length) {
    console.error('\n\ngenerate-asm-types:')
    messages.forEach(m => console.error('   ', m))
    console.error('\n\n')
    process.exit(1)
  }

  console.log('export type EcsAsm = EmscriptenModule & {')

  lines.forEach(e => console.log(e))

  console.log('}')
}

run(process.argv.slice(2))
