load("//bzl/js:js.bzl", "js_library")

package(
    default_visibility = ["//visibility:public"],
)

js_library(
    name = "deepDelete",
    srcs = [
        "deepDelete.ts",
    ],
    deps = [
        "//c8/ecs/src/8mesh/components/core:UpdateManager",
    ],
)

js_library(
    name = "Defaults",
    srcs = [
        "Defaults.ts",
    ],
    deps = [
        "//c8/ecs/src/8mesh/utils:background-size",
        "//c8/ecs/src/8mesh/utils/block-layout:AlignItems",
        "//c8/ecs/src/8mesh/utils/block-layout:ContentDirection",
        "//c8/ecs/src/8mesh/utils/block-layout:JustifyContent",
        "//c8/ecs/src/8mesh/utils/inline-layout:TextAlign",
        "//c8/ecs/src/8mesh/utils/inline-layout:Whitespace",
    ],
)

js_library(
    name = "Keymaps",
    srcs = [
        "Keymaps.ts",
    ],
)

js_library(
    name = "mix",
    srcs = [
        "mix.ts",
    ],
)

js_library(
    name = "three-types",
    srcs = [
        "three-types.ts",
    ],
)

js_library(
    name = "background-size",
    srcs = [
        "background-size.ts",
    ],
)

js_library(
    name = "set-layers-on-object",
    srcs = [
        "set-layers-on-object.ts",
    ],
)
