load("//bzl/js:js.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

js_library(
    name = "dispatchify",
    srcs = [
        "dispatchify.ts",
    ],
)

js_library(
    name = "dispatchify-types",
    srcs = [
        "dispatchify-types.ts",
    ],
)
