cc_binary(
    name = "pose_graph_3d",
    srcs = [
        "pose_graph_3d.cc",
        "pose_graph_3d_error_term.h",
        "read_g2o.h",
        "types.h",
    ],
    deps = [
        "@ceres2//:ceres",
        "@ceres2//:miniglog",
        "@com_github_gflags_gflags//:gflags",
    ],
)
