load("//bzl/js:js.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

js_library(
    name = "load-models",
    srcs = [
        "load-models.ts",
    ],
    deps = [
        "//reality/app/xr/js/src:resources",
        "//reality/app/xr/js/src/types:xrfacecc",
    ],
)
