load("//third_party/protobuf:protobuf-wrap-rules.bzl", proto_library = "proto_library_versionable")

package(
    default_visibility = ["//visibility:private"],
)

proto_library(
    name = "test_service_proto",
    srcs = [
        "test_service.proto",
    ],
    visibility = [
        "//visibility:public",
    ],
)
