import * as Types from '../types'

import {registerAttribute} from '../registry'
import {UI_DEFAULTS} from '../../shared/ui-constants'

const Ui = registerAttribute('ui', {
  type: Types.string,
  font: Types.string,
  fontSize: Types.f32,
  position: Types.string,
  opacity: Types.f32,
  backgroundOpacity: Types.f32,
  backgroundSize: Types.string,
  nineSliceBorderTop: Types.string,
  nineSliceBorderBottom: Types.string,
  nineSliceBorderLeft: Types.string,
  nineSliceBorderRight: Types.string,
  nineSliceScaleFactor: Types.f32,
  background: Types.string,
  color: Types.string,
  text: Types.string,
  image: Types.string,
  video: Types.string,
  fixedSize: Types.boolean,
  width: Types.string,
  height: Types.string,
  top: Types.string,
  left: Types.string,
  bottom: Types.string,
  right: Types.string,
  borderColor: Types.string,
  borderRadius: Types.f32,
  borderRadiusTopLeft: Types.string,
  borderRadiusTopRight: Types.string,
  borderRadiusBottomLeft: Types.string,
  borderRadiusBottomRight: Types.string,
  ignoreRaycast: Types.boolean,
  // FlexStyles
  alignContent: Types.string,
  alignItems: Types.string,
  alignSelf: Types.string,
  borderWidth: Types.f32,
  columnGap: Types.string,
  direction: Types.string,
  display: Types.string,
  flex: Types.f32,
  flexBasis: Types.string,
  flexDirection: Types.string,
  flexGrow: Types.f32,
  flexShrink: Types.f32,
  flexWrap: Types.string,
  gap: Types.string,
  justifyContent: Types.string,
  margin: Types.string,
  marginBottom: Types.string,
  marginLeft: Types.string,
  marginRight: Types.string,
  marginTop: Types.string,
  maxHeight: Types.string,
  maxWidth: Types.string,
  minHeight: Types.string,
  minWidth: Types.string,
  overflow: Types.string,
  padding: Types.string,
  paddingBottom: Types.string,
  paddingLeft: Types.string,
  paddingRight: Types.string,
  paddingTop: Types.string,
  rowGap: Types.string,
  textAlign: Types.string,
  verticalTextAlign: Types.string,
  stackingOrder: Types.f32,
}, {
  ...UI_DEFAULTS,
  font: UI_DEFAULTS.font.font,
})

export {Ui}
