load("//bzl/js:js.bzl", "js_library")

package(
    default_visibility = ["//visibility:public"],
)

js_library(
    name = "BackgroundVertex",
    srcs = [
        "background-vertex.ts",
    ],
)

js_library(
    name = "BackgroundFragment",
    srcs = [
        "background-fragment.ts",
    ],
)

js_library(
    name = "TextFragment",
    srcs = [
        "text-fragment.ts",
    ],
)

js_library(
    name = "TextVertex",
    srcs = [
        "text-vertex.ts",
    ],
)

js_library(
    name = "background-fragment",
    srcs = [
        "background-fragment.ts",
    ],
)

js_library(
    name = "background-vertex",
    srcs = [
        "background-vertex.ts",
    ],
)

js_library(
    name = "text-fragment",
    srcs = [
        "text-fragment.ts",
    ],
)

js_library(
    name = "text-vertex",
    srcs = [
        "text-vertex.ts",
    ],
)
