cc_library(
    name = "visibility",
    hdrs = ["visibility.h"],
    visibility = [
        "//visibility:public",
    ],
)

config_setting(
    name = "strip-always",
    values = {
        "compilation_mode": "opt",
    },
)
