load("//bzl/utils:embedded.bzl", "embedded_data")

package(default_visibility = [
    "//reality/engine:__subpackages__",
])

filegroup(
    name = "faces",
    testonly = 1,
    srcs = [
        "faces.jpg",
    ],
)

filegroup(
    name = "hand_left_192",
    testonly = 1,
    srcs = [
        "hand_left_192.jpg",
    ],
)

filegroup(
    name = "hand-right-up-128",
    testonly = 1,
    srcs = [
        "hand_right_up_128.jpg",
    ],
)

filegroup(
    name = "hand-left-up-224",
    testonly = 1,
    srcs = [
        "hand_left_up_224.jpg",
    ],
)

filegroup(
    name = "ear-left",
    testonly = 1,
    srcs = [
        "ear_left.jpg",
    ],
)

filegroup(
    name = "ear-right",
    testonly = 1,
    srcs = [
        "ear_right.jpg",
    ],
)

filegroup(
    name = "crop",
    testonly = 1,
    srcs = [
        "crop.jpg",
    ],
)

filegroup(
    name = "desk",
    testonly = 1,
    srcs = [
        "desk.jpg",
    ],
)

filegroup(
    name = "livingroom",
    testonly = 1,
    srcs = [
        "livingroom.jpg",
    ],
)

filegroup(
    name = "office",
    testonly = 1,
    srcs = [
        "office.png",
    ],
)

filegroup(
    name = "office9x16",
    testonly = 1,
    srcs = [
        "office_w360_h640.png",
    ],
)

embedded_data(
    name = "embedded-semantics",
    srcs = [
        "semantics_fp32.tflite",
    ],
)
