const CAMERA_DEFAULTS = {
  type: 'perspective',
  fov: 80,
  zoom: 1,
  left: -1,
  right: 1,
  top: 1,
  bottom: -1,
  xrCameraType: '3dOnly',
  phone: '3D',
  desktop: '3D',
  headset: '3D',
  nearClip: 0.1,
  farClip: 2000,
  direction: 'front',
  disableWorldTracking: false,
  enableLighting: false,
  enableWorldPoints: false,
  leftHandedAxes: false,
  mirroredDisplay: false,
  scale: 'responsive',
  enableVps: false,
  meshGeometryFace: false,
  meshGeometryEyes: false,
  meshGeometryIris: false,
  meshGeometryMouth: false,
  uvType: 'standard',
  maxDetections: 1,
  enableEars: false,
}

export {
  CAMERA_DEFAULTS,
}
