// @attr[](visibility = "//reality/app/nae/packager:__subpackages__")
// @attr[](visibility = "//c8/ecs:__subpackages__")
// @attr[](visibility = "//reality/cloud:shared")

import type {Map, MapTheme} from './scene-graph'

const DEFAULT_LAT = 37.7955281
const DEFAULT_LNG = -122.3934225
const DEFAULT_SCALE = 15
const DEFAULT_RADIUS = 500
const LAT_LNG_SLIDER_FACTOR = 1e-8

const MIN_LAT = -85.0511287798066
const MAX_LAT = 85.0511287798066
const MIN_LNG = -180
const MAX_LNG = 180
const MIN_RADIUS = 20
const MAX_RADIUS = 2e7

// map points
const DEFAULT_MIN_SCALE = 0

// gps pointer
const DEFAULT_WALK_KMH = 2
const DEFAULT_RUN_KMH = 8
const DEFAULT_DRIVE_KMH = 25

const MAP_DEFAULTS: Required<Map> = {
  latitude: DEFAULT_LAT,
  longitude: DEFAULT_LNG,
  targetEntity: {type: 'entity', id: ''},
  radius: DEFAULT_RADIUS,
  spawnLocations: false,
  useGps: true,
}

const MAP_THEME_DEFAULTS: Required<MapTheme> = {
  landColor: '#FFFFFF',
  buildingColor: '#FFFFFF',
  parkColor: '#FFFFFF',
  parkingColor: '#FFFFFF',
  roadColor: '#FFFFFF',
  sandColor: '#FFFFFF',
  transitColor: '#FFFFFF',
  waterColor: '#FFFFFF',
  landOpacity: 1,
  buildingOpacity: 1,
  parkOpacity: 1,
  parkingOpacity: 1,
  roadOpacity: 1,
  sandOpacity: 1,
  transitOpacity: 1,
  waterOpacity: 1,
  lod: 1,
  buildingBase: 0.014,
  parkBase: 0.002,
  parkingBase: 0.008,
  roadBase: 0.01,
  sandBase: 0.004,
  transitBase: 0.012,
  waterBase: 0.006,
  buildingMinMeters: 6,
  buildingMaxMeters: 6,
  roadLMeters: 8,
  roadMMeters: 4,
  roadSMeters: 2,
  roadXLMeters: 32,
  transitMeters: 8,
  waterMeters: 6,
  roadLMin: 0,
  roadMMin: 0,
  roadSMin: 0,
  roadXLMin: 0,
  transitMin: 0,
  waterMin: 0,
  landVisibility: true,
  buildingVisibility: true,
  parkVisibility: true,
  parkingVisibility: true,
  roadVisibility: true,
  sandVisibility: true,
  transitVisibility: true,
  waterVisibility: true,
}

const LAYERS = ['land', 'building', 'park', 'parking', 'sand', 'road', 'transit', 'water'] as const
const COLOR_SUFFIX = 'Color'
const OFFSET_SUFFIX = 'Base'
const OPACITY_SUFFIX = 'Opacity'
const SIZE_SUFFIX = 'Meters'
const VISIBILITY_SUFFIX = 'Visibility'

const THEME_PRESETS: Record<string, Partial<MapTheme>> = {
  none: {},
  lighttime: {
    landColor: '#ebebeb',
    buildingColor: '#dfdfdf',
    parkColor: '#d3e9d7',
    parkingColor: '#ebebeb',
    roadColor: '#ffffff',
    transitColor: '#f2c55a',
    sandColor: '#fbf0c8',
    waterColor: '#a3bff4',
  },
  nianticlight: {
    landColor: '#F8F5EB',
    buildingColor: '#E3D9C3',
    buildingOpacity: 0.4,
    parkColor: '#3D8F43',
    parkingColor: '#E8E8DB',
    roadColor: '#CFBE99',
    sandColor: '#FFE5B3',
    transitColor: '#FFC758',
    waterColor: '#43BBD1',
  },
  vaporwave: {
    landColor: '#A6DAFF',
    buildingColor: '#42E3EB',
    buildingMinMeters: 10,
    buildingMaxMeters: 1000,
    parkColor: '#EF1990',
    parkingColor: '#FE7AD0',
    roadColor: '#C3A8E5',
    transitColor: '#C3A8E5',
    sandColor: '#F9EF00',
    waterColor: '#4414F3',
  },
  muted: {
    landColor: '#E0E0E0',
    buildingColor: '#CFCFCF',
    buildingOpacity: 0.4,
    parkColor: '#C1D7C6',
    parkingColor: '#BFBFBF',
    roadColor: '#FFFFFF',
    sandColor: '#EAE9D7',
    transitColor: '#AC92A6',
    waterColor: '#B0D1DD',
  },
  rust: {
    landColor: '#E8E8DB',
    buildingColor: '#D6D6BE',
    buildingOpacity: 0.4,
    parkColor: '#BEF0B2',
    parkingColor: '#E8E8DB',
    roadColor: '#B89794',
    sandColor: '#F9F8C7',
    transitColor: '#BB7C7C',
    waterColor: '#C1F2F6',
  },
  natural: {
    landColor: '#AEC988',
    buildingColor: '#EFEFEA',
    buildingOpacity: 0.4,
    parkColor: '#80B063',
    parkingColor: '#84A172',
    roadColor: '#DCE1DE',
    sandColor: '#AC92A6',
    transitColor: '#F9F8C7',
    waterColor: '#A0D3D3',
  },
  nighttime: {
    landColor: '#2D2E43',
    // landRoughness: 1,
    buildingColor: '#414e6c',
    buildingOpacity: 0.4,
    parkColor: '#0D594D',
    parkingColor: '#464766',
    roadColor: '#535479',
    sandColor: '#573E0F',
    transitColor: '#E6AC00',
    waterColor: '#1E3579',
  },
  mars: {
    landColor: '#a35928',
    buildingColor: '#814d25',
    parkColor: '#985c2e',
    parkingColor: '#a94922',
    roadColor: '#ed8b40',
    transitColor: '#67432d',
    sandColor: '#67432d',
    waterColor: '#ef9654',
  },
  trails: {
    landColor: '#4AA951',
    // landRoughness: 0.8,
    buildingColor: '#3B8740',
    buildingOpacity: 0.8,
    buildingMinMeters: 0,
    buildingMaxMeters: 0,
    parkVisibility: false,
    parkingVisibility: false,
    roadColor: '#ECE1C3',
    // roadRoughness: 0.8,
    sandColor: '#ECE1C3',
    // sandRoughness: 0.8,
    transitVisibility: false,
    waterColor: '#58B8EF',
    // waterRoughness: 1,
  },
  arcade: {
    landColor: '#AFFFA0',
    buildingColor: '#84EDC2',
    buildingOpacity: 0.75,
    parkColor: '#08A98A',
    parkingVisibility: false,
    roadColor: '#59A499',
    sandColor: '#F9F8C7',
    transitColor: '#59A499',
    waterColor: '#1A87D6',
  },
  nightlime: {
    landColor: '#11053b',
    buildingColor: '#1a0a52',
    parkColor: '#1a0a52',
    parkingColor: '#1a0a52',
    roadColor: '#d6fe5e',
    transitColor: '#1a0a52',
    sandColor: '#2c0977',
    waterColor: '#012f7b',
    roadSMeters: 0.5,
    roadMMeters: 1,
    roadLMeters: 2,
    roadXLMeters: 4,
    transitMeters: 4,
    waterMeters: 3,
  },
  violetsunset: {
    landColor: '#ff8c82',
    buildingColor: '#503953',
    parkColor: '#88c084',
    parkingColor: '#998FC7',
    roadColor: '#503953',
    transitColor: '#BE5F84',
    sandColor: '#FFAD72',
    waterColor: '#54b2af',
    roadSMeters: 3,
    roadMMeters: 3,
    roadLMeters: 3,
    roadXLMeters: 3,
    transitMeters: 3,
  },
  ice: {
    landColor: '#cbf0ff',
    buildingColor: '#93e3fd',
    parkColor: '#ffffff',
    parkingColor: '#ffffff',
    roadColor: '#ffffff',
    transitColor: '#52d6fc',
    sandColor: '#fefcdd',
    waterColor: '#0042a9',
  },
  seaside: {
    landColor: '#efeff1',
    buildingColor: '#ffdbd8',
    parkColor: '#22708d',
    parkingColor: '#3e89a9',
    roadColor: '#7ec0c1',
    transitColor: '#2f61da',
    sandColor: '#e1e1ea',
    waterColor: '#59b5e2',
  },
  swamp: {
    landColor: '#425930',
    buildingColor: '#162d10',
    parkColor: '#c3c78f',
    parkingColor: '#4c611f',
    roadColor: '#7f8c3b',
    transitColor: '#101e11',
    sandColor: '#56512c',
    waterColor: '#26504f',
  },
  homerun: {
    landColor: '#ecebe1',
    buildingColor: '#efeff0',
    parkColor: '#ecebe1',
    parkingColor: '#f1f3f4',
    roadColor: '#1f4e8c',
    transitColor: '#ca4541',
    sandColor: '#ecebe1',
    waterColor: '#ecebe1',
  },
  eighthwalldark: {
    landColor: '#ad50ff',
    buildingColor: '#7611b6',
    parkColor: '#01ecaf',
    parkingColor: '#464766',
    roadColor: '#464766',
    transitColor: '#ffc828',
    sandColor: '#b6b8d0',
    waterColor: '#2d2e43',
  },
  bubblegum: {
    landColor: '#d0a9b1',
    buildingColor: '#bfe1d4',
    parkColor: '#f7e9e1',
    parkingColor: '#e0828f',
    roadColor: '#f7e9e1',
    transitColor: '#4898b1',
    sandColor: '#f7e9e1',
    waterColor: '#4898b1',
    transitMeters: 4,
  },
  newspaper: {
    landColor: '#d6d6d6',
    buildingColor: '#c2c2c2',
    parkColor: '#adadad',
    parkingColor: '#707070',
    roadColor: '#000000',
    transitColor: '#000000',
    sandColor: '#707070',
    waterColor: '#858585',
  },
  rollerrink: {
    landColor: '#70f1d5',
    buildingColor: '#e065b2',
    parkColor: '#9260de',
    parkingColor: '#fae561',
    roadColor: '#54b8f3',
    transitColor: '#fae561',
    sandColor: '#e065b2',
    waterColor: '#54b8f3',
  },
}

export {
  MAP_DEFAULTS,
  MAP_THEME_DEFAULTS,
  DEFAULT_LAT,
  DEFAULT_LNG,
  DEFAULT_RADIUS,
  DEFAULT_SCALE,
  LAT_LNG_SLIDER_FACTOR,
  DEFAULT_MIN_SCALE,
  MIN_LAT,
  MAX_LAT,
  MIN_LNG,
  MAX_LNG,
  MIN_RADIUS,
  MAX_RADIUS,
  DEFAULT_WALK_KMH,
  DEFAULT_RUN_KMH,
  DEFAULT_DRIVE_KMH,
  LAYERS,
  COLOR_SUFFIX,
  OFFSET_SUFFIX,
  OPACITY_SUFFIX,
  SIZE_SUFFIX,
  VISIBILITY_SUFFIX,
  THEME_PRESETS,
}
