const VERTEX_POSITION_STRIDE = 3
const TARGET_ERROR = 0.05
const TARGET_INDEX_RATIO = 0.005

const TRIANGLE_VERTEX_COUNT = 3

const VERTEX_ROUNDING_FACTOR = 1000

export {
  VERTEX_POSITION_STRIDE,
  TARGET_ERROR,
  TARGET_INDEX_RATIO,
  TRIANGLE_VERTEX_COUNT,
  VERTEX_ROUNDING_FACTOR,
}
