const DEFAULT_MASS = 0
const DEFAULT_LINEAR_DAMPING = 0
const DEFAULT_ANGULAR_DAMPING = 0
const DEFAULT_FRICTION = 0.5
const DEFAULT_ROLLING_FRICTION = 0
const DEFAULT_SPINNING_FRICTION = 0
const DEFAULT_RESTITUTION = 0
const DEFAULT_GRAVITY_FACTOR = 1
const DEFAULT_OFFSET = 0
const DEFAULT_OFFSET_QUATERNION_X = 0
const DEFAULT_OFFSET_QUATERNION_Y = 0
const DEFAULT_OFFSET_QUATERNION_Z = 0
const DEFAULT_OFFSET_QUATERNION_W = 1
const DEFAULT_SIMPLIFICATION_MODE = 'convex'

export {
  DEFAULT_MASS,
  DEFAULT_LINEAR_DAMPING,
  DEFAULT_ANGULAR_DAMPING,
  DEFAULT_FRICTION,
  DEFAULT_ROLLING_FRICTION,
  DEFAULT_SPINNING_FRICTION,
  DEFAULT_RESTITUTION,
  DEFAULT_GRAVITY_FACTOR,
  DEFAULT_OFFSET,
  DEFAULT_OFFSET_QUATERNION_X,
  DEFAULT_OFFSET_QUATERNION_Y,
  DEFAULT_OFFSET_QUATERNION_Z,
  DEFAULT_OFFSET_QUATERNION_W,
  DEFAULT_SIMPLIFICATION_MODE,
}
