const DEFAULT_SIZE = 1000
const DEFAULT_WIDTH_SEGMENTS = 60
const DEFAULT_HEIGHT_SEGMENTS = 40

const DEFAULT_TOP_COLOR = '#464766'  // gray5
const DEFAULT_BOTTOM_COLOR = '#08061F'

const ISOLATION_TOP_COLOR = '#595959'
const ISOLATION_BOTTOM_COLOR = '#171717'

const MIN_GRADIENT_COLORS = 2
const MAX_GRADIENT_COLORS = 5

const BACKGROUND_SKYBOX_ORDER = -2000

export {
  DEFAULT_SIZE,
  DEFAULT_WIDTH_SEGMENTS,
  DEFAULT_HEIGHT_SEGMENTS,
  DEFAULT_TOP_COLOR,
  DEFAULT_BOTTOM_COLOR,
  ISOLATION_TOP_COLOR,
  ISOLATION_BOTTOM_COLOR,
  MIN_GRADIENT_COLORS,
  MAX_GRADIENT_COLORS,
  BACKGROUND_SKYBOX_ORDER,
}
