// This file was autogenerated using generate-client-definitions.ts

// npm run generate-model-definitions

// These definitions represent what the database entries look like when they're sent over the wire.

// Since the client does extra processing before the data goes into redux, we define IApp for
// example which should generally be used instead of using App directly from db.ts.

/* eslint-disable camelcase, quotes, max-len */

import type {TermsAgreements} from '../../../shared/tos'
import type {SpecialFeatureFlag} from '../../../shared/special-features'
import type {UserEditorSettings} from '../../../shared/user-editor-settings'
import type {GenerateRequestInput} from '../../../shared/genai/types/generate'
import type {Permissions} from '../../../shared/nae/nae-types'

interface Account {
  uuid: NonNullable<string>
  name: string | null
  url: string | null
  status: AccountStatus | null
  shortName: NonNullable<string>
  webOrigin: boolean | null
  webPrivate: boolean | null
  webPublic: boolean | null
  stripeId: string | null
  accountSubscriptionId: string | null
  accountLicenseSubscriptionItemId: string | null
  accountType: NonNullable<string>
  overQuotaUntil: string | null
  subscriptionItem: string | null
  lastBillingClose: string | null
  violationStatus: NonNullable<string>
  pendingCancellation: NonNullable<string>
  additionalLicensesSubItemId: string | null
  connectedDomain: string | null
  domainAssociationId: string | null
  bio: string | null
  publicFeatured: boolean | null
  icon: string | null
  trialStatus: NonNullable<AccountTrialStatus>
  trialUntil: string | null
  defaultAppLicenseInvoicePaymentsAllowed: NonNullable<boolean>
  accountLicenseInvoiceLineItemId: string | null
  googleMapsPlaceId: string | null
  googleMapsPlaceIdUpdatedAt: string | null
  contactUrl: string | null
  verifiedPartner: NonNullable<boolean>
  verifiedPremierePartner: NonNullable<boolean>
  apiAccessOverride: NonNullable<boolean>
  twitterHandle: string | null
  linkedInHandle: string | null
  youtubeHandle: string | null
  stripeConnectAccountId: string | null
  developerId: string | null
  specialFeatures: Array<SpecialFeatureFlag> | null
  accountSubscriptionScheduleId: string | null
  adEnabled: boolean | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface AccountContractAgreement {
  AccountUuid: NonNullable<string>
  ContractUuid: NonNullable<string>
  acceptedBy: NonNullable<string>
  acceptedAt: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface AccountShortName {
  name: NonNullable<string>
  AccountUuid: NonNullable<string>
  status: NonNullable<AccountShortNameStatus>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface App {
  uuid: NonNullable<string>
  status: AppStatus | null
  appName: string | null
  appKey: string | null
  AccountUuid: NonNullable<string>
  createdBy: string | null
  keyTimestamp: number | null
  version: string | null
  prevEngine: string | null
  isWeb: boolean | null
  shortLink: string | null
  webUrl: string | null
  webOrigins: string[] | null
  isCommercial: NonNullable<boolean>
  isPublic: boolean | null
  webReviewRequestedBy: string | null
  webReviewStatus: NonNullable<AppWebReviewStatus>
  webVersionStaging: string | null
  webVersionReview: string | null
  webVersionProduction: string | null
  webBackingUuid: string | null
  passphrase: string | null
  subscriptionItem: string | null
  violationStatus: NonNullable<string>
  ContractUuid: string | null
  commercialStatus: AppCommercialStatus | null
  endingAt: string | null
  subscriptionId: string | null
  usageSubscriptionItemId: string | null
  licenseSubscriptionItemId: string | null
  legacyAccountType: string | null
  campaignRedirectUrl: string | null
  devSubStartDate: string | null
  devSubPlanId: string | null
  campaignSubStartDate: string | null
  campaignSubPlanId: string | null
  launchPackageId: string | null
  appDescription: string | null
  coverImageId: string | null
  appTitle: string | null
  repoStatus: NonNullable<AppRepoStatus>
  repoLicenseMaster: string | null
  repoLicenseProd: string | null
  connectedDomain: string | null
  domainAssociationId: string | null
  buildSettingsSplashScreen: NonNullable<AppBuildSettingsSplashScreen>
  hasPwaEnabled: NonNullable<boolean>
  publicFeatured: boolean | null
  assetLimitOverrides: string | null
  hasRecurringLicense: NonNullable<boolean>
  licenseInvoiceLineItemId: string | null
  featuredPreviewDisabled: NonNullable<boolean>
  featuredDescriptionId: string | null
  featuredVideoUrl: string | null
  publishedAt: string | null
  productionCommitHash: string | null
  repoId: string | null
  hostingType: NonNullable<AppHostingType>
  defaultSimulatorSequence: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface Contract {
  uuid: NonNullable<string>
  AccountUuid: string | null
  createdBy: NonNullable<number>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  expirationDate: NonNullable<string>
  isReusable: NonNullable<boolean>
  name: NonNullable<string>
  startDate: NonNullable<string>
  signedDate: string | null
  hasPublicityRights: NonNullable<boolean>
  pdfPath: NonNullable<string>
  isAvailableAsCanned: boolean | null
  invoicePaymentsAllowed: boolean | null
  isRecurringContract: NonNullable<boolean>
}

interface ContractItem {
  uuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  AppUuid: NonNullable<string>
  ContractUuid: NonNullable<string>
  amount: NonNullable<number>
  startDate: NonNullable<string>
  endDate: NonNullable<string>
  canceledAt: string | null
  stripeInvoiceId: NonNullable<string>
  stripeInvoiceItemId: NonNullable<string>
}

interface ContractTemplate {
  uuid: NonNullable<string>
  name: string | null
  description: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  ContractUuid: NonNullable<string>
  amount: NonNullable<number>
  interval: NonNullable<ContractTemplateInterval>
  intervalCount: NonNullable<number>
  daysUntilDue: NonNullable<number>
  type: NonNullable<ContractTemplateType>
  billingScheme: NonNullable<ContractTemplateBillingScheme>
  stripeSubPlanId: string | null
  stripeUsagePlanId: string | null
  packageId: string | null
}

interface ContractTier {
  uuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  flat_amount: NonNullable<number>
  unit_amount: NonNullable<number>
  up_to: number | null
  ContractTemplateUuid: NonNullable<string>
}

interface ImageTarget {
  uuid: NonNullable<string>
  type: NonNullable<ImageTargetType>
  AppUuid: string | null
  name: string | null
  originalImagePath: string | null
  imagePath: string | null
  luminanceImagePath: string | null
  thumbnailImagePath: string | null
  geometryTexturePath: string | null
  scanDataPath: string | null
  status: ImageTargetStatus | null
  userMetadata: string | null
  moveable: NonNullable<boolean>
  physicalWidthInMeters: number | null
  metadata: string | null
  isRotated: NonNullable<boolean>
  userMetadataIsJson: NonNullable<boolean>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface Invite {
  AccountUuid: NonNullable<string>
  email: NonNullable<string>
  from: string | null
  token: string | null
  ReferralCodeUuid: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface NaeInfo {
  uuid: NonNullable<string>
  AppUuid: NonNullable<string>
  platform: NonNullable<NaeInfoPlatform>
  publisher: string | null
  displayName: string | null
  bundleId: string | null
  iconId: string | null
  launchScreenIconId: string | null
  permissions: Permissions | null
  lastBuiltVersionName: string | null
  lastBuiltVersionCode: number | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface NaePackagerBuild {
  version: NonNullable<string>
  timestamp: NonNullable<string>
  status: NaePackagerBuildStatus | null
  buildType: NaePackagerBuildBuildType | null
  byteSize: number | null
  filename: string | null
  sha256: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface NaePackagerChannel {
  name: NonNullable<NaePackagerChannelName>
  version: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface NaePackagerVersionState {
  name: NonNullable<NaePackagerVersionStateName>
  major: NonNullable<number>
  minor: NonNullable<number>
  patch: NonNullable<number>
  main: NonNullable<number>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface PolicyViolation {
  uuid: NonNullable<string>
  violationType: NonNullable<string>
  status: NonNullable<string>
  resolvedAt: string | null
  AccountUuid: string | null
  AppUuid: string | null
  creatorId: NonNullable<number>
  resolverId: number | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface PwaInfo {
  uuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  name: string | null
  shortName: string | null
  iconId: string | null
  backgroundColor: string | null
  themeColor: string | null
  AppUuid: NonNullable<string>
}

interface ScheduledSubscription {
  uuid: NonNullable<string>
  AppUuid: NonNullable<string>
  startDate: NonNullable<string>
  planId: NonNullable<string>
  paymentSource: string | null
  collectionMethod: NonNullable<ScheduledSubscriptionCollectionMethod>
  completedAt: string | null
  scheduledStatus: NonNullable<ScheduledSubscriptionScheduledStatus>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface UserAccount {
  UserUuid: NonNullable<string>
  AccountUuid: NonNullable<string>
  role: UserAccountRole | null
  handle: string | null
  firebaseId: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface UserAppPref {
  UserUuid: NonNullable<string>
  AppUuid: NonNullable<string>
  accessDate: string | null
  activeBrowser: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface ApiKey {
  uuid: NonNullable<string>
  secretKey: NonNullable<string>
  status: NonNullable<ApiKeyStatus>
  name: NonNullable<string>
  AccountUuid: NonNullable<string>
  fullAccountAccess: boolean | null
  keyId: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface AppTag {
  uuid: NonNullable<string>
  name: NonNullable<string>
  restricted: NonNullable<boolean>
  blocked: NonNullable<boolean>
  suggestedTag: NonNullable<boolean>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface AppTagMap {
  uuid: NonNullable<string>
  AppUuid: NonNullable<string>
  AppTagUuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface FeaturedAppImage {
  uuid: NonNullable<string>
  AppUuid: string | null
  ModuleUuid: string | null
  objectId: NonNullable<string>
  status: NonNullable<FeaturedAppImageStatus>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface Module {
  uuid: NonNullable<string>
  status: NonNullable<ModuleStatus>
  AccountUuid: NonNullable<string>
  name: NonNullable<string>
  repoId: string | null
  title: string | null
  description: string | null
  coverImageId: string | null
  publicFeatured: NonNullable<boolean>
  featuredDescriptionId: string | null
  featuredVideoUrl: string | null
  compatibility: NonNullable<ModuleCompatibility>
  repoVisibility: NonNullable<ModuleRepoVisibility>
  archived: NonNullable<boolean>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface DiscoveryApp {
  uuid: NonNullable<string>
  hidden: boolean | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface ModuleUser {
  UserUuid: NonNullable<string>
  ModuleUuid: NonNullable<string>
  accessDate: string | null
  activeBrowser: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface CrossAccountPermission {
  uuid: NonNullable<string>
  FromAccountUuid: NonNullable<string>
  ToAccountUuid: NonNullable<string>
  AppUuid: string | null
  status: CrossAccountPermissionStatus | null
  inviteToken: string | null
  invitedAt: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface DependencySet {
  uuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  AppUuid: NonNullable<string>
  data: NonNullable<{dependenciesById: unknown}>
}

interface ModuleTagMap {
  uuid: NonNullable<string>
  ModuleUuid: NonNullable<string>
  AppTagUuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface AdSubmission {
  uuid: NonNullable<string>
  commitId: NonNullable<string>
  AppUuid: NonNullable<string>
  requestUuid: string | null
  reviewStatus: NonNullable<AdSubmissionReviewStatus>
  url: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  reviewedAt: string | null
  decisionExplanation: string | null
}

interface AppEngagementMetric {
  dt: NonNullable<string>
  appKey: NonNullable<string>
  meanPageTimeMs: NonNullable<number>
  totalSessions: NonNullable<number>
  sampledSessions: NonNullable<number>
}

interface User {
  uuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  crmId: string | null
  newsletterId: string | null
  emailVerifyTime: string | null
  handle: string | null
  themeSettings: Partial<UserEditorSettings> | null
  tosAgreements: TermsAgreements | null
  primaryContactEmail: NonNullable<string>
  givenName: string | null
  familyName: string | null
  locale: NonNullable<string>
  phoneNumber: string | null
  phoneNumberVerified: boolean | null
  emailVerified: boolean | null
  hasFirstTimePublished: boolean | null
  profileIcon: string | null
  latestActivityDate: string | null
  lastSeenReleasePopupId: string | null
}

interface UserLoginMethods {
  uuid: NonNullable<string>
  UserUuid: NonNullable<string>
  email: NonNullable<string>
  provider: NonNullable<UserLoginMethodsProvider>
  thirdPartyUserId: NonNullable<string>
  createdAt: string | null
  updatedAt: NonNullable<string>
  deletedAt: string | null
}

interface PlayerUser {
  UserUuid: NonNullable<string>
  playerId: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface AssetRequest {
  uuid: NonNullable<string>
  AccountUuid: NonNullable<string>
  UserUuid: NonNullable<string>
  ParentRequestUuid: string | null
  totalActionQuantity: number | null
  input: Partial<GenerateRequestInput> | null
  type: AssetRequestType | null
  status: NonNullable<AssetRequestStatus>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface AssetGeneration {
  uuid: NonNullable<string>
  RequestUuid: NonNullable<string>
  AccountUuid: NonNullable<string>
  UserUuid: NonNullable<string>
  assetType: NonNullable<AssetGenerationAssetType>
  modelName: NonNullable<string>
  prompt: string | null
  negativePrompt: string | null
  style: string | null
  seed: NonNullable<string>
  metadata: Record<string, unknown> | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface WayspotAnchor {
  uuid: NonNullable<string>
  AppUuid: NonNullable<string>
  approxLat: NonNullable<number>
  approxLng: NonNullable<number>
  name: NonNullable<string>
  payload: NonNullable<string>
  poiId: NonNullable<string>
  poiHashedId: string | null
  poiTitle: string | null
  poiImage: string | null
  nodeId: NonNullable<string>
  spaceId: string | null
  hasMegaModeMesh: boolean | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface CreditGrant {
  uuid: NonNullable<string>
  AccountUuid: NonNullable<string>
  category: NonNullable<CreditGrantCategory>
  quantity: NonNullable<number>
  remainingQuantity: NonNullable<number>
  unitPrice: NonNullable<number>
  totalPrice: NonNullable<number>
  unitValue: NonNullable<number>
  totalValue: NonNullable<number>
  effectiveAt: NonNullable<string>
  expiresAt: NonNullable<string>
  status: NonNullable<CreditGrantStatus>
  anchorDate: string | null
  description: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface Feature {
  uuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  category: NonNullable<FeatureCategory>
  featureName: NonNullable<string>
  optionName: NonNullable<string>
  status: NonNullable<FeatureStatus>
  billingType: NonNullable<FeatureBillingType>
  subscriptionId: string | null
  subscriptionItemId: string | null
  subscriptionScheduleId: string | null
  subscriptionEndsAt: string | null
}

interface Transaction {
  uuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
  AccountUuid: NonNullable<string>
  productId: NonNullable<string>
  priceId: NonNullable<string>
  invoiceId: NonNullable<string>
  invoiceItemId: string | null
  invoiceLineItemId: NonNullable<string>
}

interface AccountFeatureMap {
  uuid: NonNullable<string>
  AccountUuid: NonNullable<string>
  FeatureUuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface FeatureTransactionMap {
  uuid: NonNullable<string>
  FeatureUuid: NonNullable<string>
  TransactionUuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface CreditGrantTransactionMap {
  uuid: NonNullable<string>
  CreditGrantUuid: NonNullable<string>
  TransactionUuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface CreditBalanceTransaction {
  uuid: NonNullable<string>
  AccountUuid: NonNullable<string>
  type: NonNullable<CreditBalanceTransactionType>
  description: string | null
  UserUuid: string | null
  CreditGrantUuid: NonNullable<string>
  quantity: NonNullable<number>
  value: NonNullable<number>
  CreditServicePricingUuid: string | null
  totalActionQuantity: NonNullable<number>
  totalActionValue: NonNullable<number>
  AssetRequestUuid: string | null
  redeemStatus: CreditBalanceTransactionRedeemStatus | null
  requestId: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface CreditServicePricing {
  uuid: NonNullable<string>
  feature: NonNullable<CreditServicePricingFeature>
  requestType: NonNullable<CreditServicePricingRequestType>
  requestPrice: NonNullable<number>
  AiModelUuid: string | null
  status: NonNullable<CreditServicePricingStatus>
  UserUuid: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface ReferralCode {
  uuid: NonNullable<string>
  code: NonNullable<string>
  AccountUuid: NonNullable<string>
  createdAt: NonNullable<string>
  deletedAt: string | null
  updatedAt: NonNullable<string>
}

interface ReferralCodeReward {
  uuid: NonNullable<string>
  name: NonNullable<string>
  referrerCreditAmount: NonNullable<number>
  refereeCreditAmount: NonNullable<number>
  isActive: boolean | null
  createdAt: string | null
  updatedAt: NonNullable<string>
}

interface ReferralCodeRedemption {
  uuid: NonNullable<string>
  ReferralCodeUuid: NonNullable<string>
  ReferralCodeRewardUuid: NonNullable<string>
  UserUuid: NonNullable<string>
  createdAt: string | null
  source: NonNullable<ReferralCodeRedemptionSource>
  status: NonNullable<ReferralCodeRedemptionStatus>
  updatedAt: NonNullable<string>
}

interface AiModel {
  uuid: NonNullable<string>
  serviceProvider: NonNullable<string>
  modelProvider: NonNullable<string>
  modelFamily: NonNullable<string>
  modelId: NonNullable<string>
  status: NonNullable<AiModelStatus>
  UserUuid: string | null
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface AppFeatureMap {
  uuid: NonNullable<string>
  AppUuid: NonNullable<string>
  FeatureUuid: NonNullable<string>
  createdAt: NonNullable<string>
  updatedAt: NonNullable<string>
}

interface Tables {
  Accounts: Account
  AccountContractAgreements: AccountContractAgreement
  AccountShortNames: AccountShortName
  Apps: App
  Contracts: Contract
  ContractItems: ContractItem
  ContractTemplates: ContractTemplate
  ContractTiers: ContractTier
  ImageTargets: ImageTarget
  Invites: Invite
  NaeInfos: NaeInfo
  NaePackagerBuilds: NaePackagerBuild
  NaePackagerChannels: NaePackagerChannel
  NaePackagerVersionStates: NaePackagerVersionState
  PolicyViolations: PolicyViolation
  PwaInfos: PwaInfo
  ScheduledSubscriptions: ScheduledSubscription
  UserAccounts: UserAccount
  UserAppPrefs: UserAppPref
  ApiKeys: ApiKey
  AppTags: AppTag
  AppTagMaps: AppTagMap
  FeaturedAppImages: FeaturedAppImage
  Modules: Module
  DiscoveryApps: DiscoveryApp
  ModuleUsers: ModuleUser
  CrossAccountPermissions: CrossAccountPermission
  DependencySets: DependencySet
  ModuleTagMaps: ModuleTagMap
  AdSubmissions: AdSubmission
  AppEngagementMetrics: AppEngagementMetric
  Users: User
  UserLoginMethods: UserLoginMethods
  PlayerUsers: PlayerUser
  AssetRequests: AssetRequest
  AssetGenerations: AssetGeneration
  WayspotAnchors: WayspotAnchor
  CreditGrants: CreditGrant
  Features: Feature
  Transactions: Transaction
  AccountFeatureMaps: AccountFeatureMap
  FeatureTransactionMaps: FeatureTransactionMap
  CreditGrantTransactionMaps: CreditGrantTransactionMap
  CreditBalanceTransactions: CreditBalanceTransaction
  CreditServicePricings: CreditServicePricing
  ReferralCodes: ReferralCode
  ReferralCodeRewards: ReferralCodeReward
  ReferralCodeRedemptions: ReferralCodeRedemption
  AiModels: AiModel
  AppFeatureMaps: AppFeatureMap
}

type AccountStatus = "UNKNOWN" | "ENABLED" | "DISABLED" | "DELETED" | "ACTIVATING"
type AccountTrialStatus = "NONE" | "ACCOUNT" | "BILLING" | "ACTIVE" | "CANCELED" | "ENDED" | "UPGRADED" | "VIOLATION" | "INELIGIBLE" | "VOIDED"
type AccountShortNameStatus = "ACTIVE" | "DELETED"
type AppStatus = "UNKNOWN" | "ENABLED" | "DISABLED" | "DELETED"
type AppWebReviewStatus = "UNKNOWN" | "PENDING" | "APPROVED" | "REJECTED" | "COMPLETED"
type AppCommercialStatus = "DEMO" | "DEVELOP" | "LAUNCH" | "COMPLETE" | "CANCELED"
type AppRepoStatus = "UNKNOWN" | "NONE" | "PRIVATE" | "PUBLIC"
type AppBuildSettingsSplashScreen = "UNKNOWN" | "DEFAULT" | "DISABLED" | "DEMO" | "NONCOMMERCIAL" | "EDUCATIONAL" | "APP"
type AppHostingType = "UNSET" | "CLOUD_EDITOR" | "CLOUD_STUDIO" | "SELF" | "INTERNAL" | "AD"
type ContractTemplateInterval = "DAY" | "WEEK" | "MONTH"
type ContractTemplateType = "DEMO" | "DEV" | "DEV_EXT" | "CAMPAIGN" | "CAMPAIGN_EXT"
type ContractTemplateBillingScheme = "PER_UNIT" | "TIERED"
type ImageTargetType = "UNSPECIFIED" | "PLANAR" | "CYLINDER" | "CONICAL" | "SCAN"
type ImageTargetStatus = "UNKNOWN" | "ENABLED" | "DISABLED" | "DELETED" | "DRAFT" | "TAKEN_DOWN"
type NaeInfoPlatform = "ANDROID" | "IOS"
type NaePackagerBuildStatus = "COMPLETED" | "FAILED" | "PENDING"
type NaePackagerBuildBuildType = "branch" | "main"
type NaePackagerChannelName = "branch" | "beta" | "release" | "dev"
type NaePackagerVersionStateName = "main" | "branch"
type ScheduledSubscriptionCollectionMethod = "send_invoice" | "charge_automatically"
type ScheduledSubscriptionScheduledStatus = "DEVELOP" | "LAUNCH"
type UserAccountRole = "OWNER" | "ADMIN" | "DEV" | "BILLMANAGER"
type ApiKeyStatus = "ENABLED" | "DISABLED" | "DELETED"
type FeaturedAppImageStatus = "DRAFT" | "FEATURED" | "DELETED" | "DISABLED"
type ModuleStatus = "ACTIVE" | "DELETED"
type ModuleCompatibility = "UNSET" | "CLOUD_EDITOR_ONLY" | "SELF_ONLY" | "ANY" | "CLOUD_STUDIO_ONLY" | "EDITOR_SELF" | "SELF_STUDIO" | "EDITOR_STUDIO"
type ModuleRepoVisibility = "PRIVATE" | "PUBLIC"
type CrossAccountPermissionStatus = "INVITED" | "ACTIVE" | "DELETED"
type AdSubmissionReviewStatus = "APPROVED" | "PENDING" | "REJECTED"
type UserLoginMethodsProvider = "EMAIL" | "GOOGLE" | "APPLE"
type AssetRequestType = "TEXT_TO_IMAGE" | "IMAGE_TO_IMAGE" | "IMAGE_TO_MESH" | "MESH_TO_ANIMATION"
type AssetRequestStatus = "REQUESTED" | "PROCESSING" | "SUCCESS" | "FAILED"
type AssetGenerationAssetType = "IMAGE" | "MESH"
type CreditGrantCategory = "PAID_PLAN" | "PAID_TOPUP" | "FREE_STANDARD" | "FREE_PROMOTION"
type CreditGrantStatus = "GRANTED" | "VOIDED"
type FeatureCategory = "ACCOUNT" | "APP"
type FeatureStatus = "ENABLED" | "DISABLED" | "VOIDED"
type FeatureBillingType = "RECURRING" | "ONE_TIME"
type CreditBalanceTransactionType = "BUY" | "GRANT" | "REDEEM" | "REFUND" | "ADJUST"
type CreditBalanceTransactionRedeemStatus = "PENDING" | "COMPLETED" | "FAILED" | "TIMED_OUT"
type CreditServicePricingFeature = "ASSET_GEN" | "NAE"
type CreditServicePricingRequestType = "TEXT_TO_IMAGE" | "IMAGE_TO_IMAGE" | "IMAGE_TO_MESH" | "MESH_TO_ANIMATION" | "ANDROID" | "IOS" | "HTML"
type CreditServicePricingStatus = "ACTIVE" | "INACTIVE" | "QA"
type ReferralCodeRedemptionSource = "SIGNUP" | "EMAIL" | "UNKNOWN"
type ReferralCodeRedemptionStatus = "PENDING" | "PAID" | "REJECTED"
type AiModelStatus = "ACTIVE" | "INACTIVE" | "QA"

export type {
  Account,
  AccountContractAgreement,
  AccountFeatureMap,
  AccountShortName,
  AccountShortNameStatus,
  AccountStatus,
  AccountTrialStatus,
  AdSubmission,
  AdSubmissionReviewStatus,
  AiModel,
  AiModelStatus,
  ApiKey,
  ApiKeyStatus,
  App,
  AppBuildSettingsSplashScreen,
  AppCommercialStatus,
  AppEngagementMetric,
  AppFeatureMap,
  AppHostingType,
  AppRepoStatus,
  AppStatus,
  AppTag,
  AppTagMap,
  AppWebReviewStatus,
  AssetGeneration,
  AssetGenerationAssetType,
  AssetRequest,
  AssetRequestStatus,
  AssetRequestType,
  Contract,
  ContractItem,
  ContractTemplate,
  ContractTemplateBillingScheme,
  ContractTemplateInterval,
  ContractTemplateType,
  ContractTier,
  CreditBalanceTransaction,
  CreditBalanceTransactionRedeemStatus,
  CreditBalanceTransactionType,
  CreditGrant,
  CreditGrantCategory,
  CreditGrantStatus,
  CreditGrantTransactionMap,
  CreditServicePricing,
  CreditServicePricingFeature,
  CreditServicePricingRequestType,
  CreditServicePricingStatus,
  CrossAccountPermission,
  CrossAccountPermissionStatus,
  DependencySet,
  DiscoveryApp,
  Feature,
  FeatureBillingType,
  FeatureCategory,
  FeaturedAppImage,
  FeaturedAppImageStatus,
  FeatureStatus,
  FeatureTransactionMap,
  ImageTarget,
  ImageTargetStatus,
  ImageTargetType,
  Invite,
  Module,
  ModuleCompatibility,
  ModuleRepoVisibility,
  ModuleStatus,
  ModuleTagMap,
  ModuleUser,
  NaeInfo,
  NaeInfoPlatform,
  NaePackagerBuild,
  NaePackagerBuildBuildType,
  NaePackagerBuildStatus,
  NaePackagerChannel,
  NaePackagerChannelName,
  NaePackagerVersionState,
  NaePackagerVersionStateName,
  PlayerUser,
  PolicyViolation,
  PwaInfo,
  ReferralCode,
  ReferralCodeRedemption,
  ReferralCodeRedemptionSource,
  ReferralCodeRedemptionStatus,
  ReferralCodeReward,
  ScheduledSubscription,
  ScheduledSubscriptionCollectionMethod,
  ScheduledSubscriptionScheduledStatus,
  Tables,
  Transaction,
  User,
  UserAccount,
  UserAccountRole,
  UserAppPref,
  UserLoginMethods,
  UserLoginMethodsProvider,
  WayspotAnchor,
  Account as Accounts,
  AccountContractAgreement as AccountContractAgreements,
  AccountFeatureMap as AccountFeatureMaps,
  AccountShortName as AccountShortNames,
  AccountShortNameStatus as enum_AccountShortNames_status,
  AccountStatus as enum_Accounts_status,
  AccountTrialStatus as enum_Accounts_trialStatus,
  AdSubmission as AdSubmissions,
  AdSubmissionReviewStatus as enum_AdSubmissions_reviewStatus,
  AiModel as AiModels,
  AiModelStatus as enum_AiModels_status,
  ApiKey as ApiKeys,
  ApiKeyStatus as enum_ApiKeys_status,
  App as Apps,
  AppBuildSettingsSplashScreen as enum_Apps_buildSettingsSplashScreen,
  AppCommercialStatus as enum_Apps_commercialStatus,
  AppEngagementMetric as AppEngagementMetrics,
  AppFeatureMap as AppFeatureMaps,
  AppHostingType as enum_Apps_hostingType,
  AppRepoStatus as enum_Apps_repoStatus,
  AppStatus as enum_Apps_status,
  AppTag as AppTags,
  AppTagMap as AppTagMaps,
  AppWebReviewStatus as enum_Apps_webReviewStatus,
  AssetGeneration as AssetGenerations,
  AssetGenerationAssetType as enum_AssetGenerations_assetType,
  AssetRequest as AssetRequests,
  AssetRequestStatus as enum_AssetRequests_status,
  AssetRequestType as enum_AssetRequests_type,
  Contract as Contracts,
  ContractItem as ContractItems,
  ContractTemplate as ContractTemplates,
  ContractTemplateBillingScheme as enum_ContractTemplates_billingScheme,
  ContractTemplateInterval as enum_ContractTemplates_interval,
  ContractTemplateType as enum_ContractTemplates_type,
  ContractTier as ContractTiers,
  CreditBalanceTransaction as CreditBalanceTransactions,
  CreditBalanceTransactionRedeemStatus as enum_CreditBalanceTransactions_redeemStatus,
  CreditBalanceTransactionType as enum_CreditBalanceTransactions_type,
  CreditGrant as CreditGrants,
  CreditGrantCategory as enum_CreditGrants_category,
  CreditGrantStatus as enum_CreditGrants_status,
  CreditGrantTransactionMap as CreditGrantTransactionMaps,
  CreditServicePricing as CreditServicePricings,
  CreditServicePricingFeature as enum_CreditServicePricings_feature,
  CreditServicePricingRequestType as enum_CreditServicePricings_requestType,
  CreditServicePricingStatus as enum_CreditServicePricings_status,
  CrossAccountPermission as CrossAccountPermissions,
  CrossAccountPermissionStatus as enum_CrossAccountPermissions_status,
  DependencySet as DependencySets,
  DiscoveryApp as DiscoveryApps,
  Feature as Features,
  FeatureBillingType as enum_Features_billingType,
  FeatureCategory as enum_Features_category,
  FeaturedAppImage as FeaturedAppImages,
  FeaturedAppImageStatus as enum_FeaturedAppImages_status,
  FeatureStatus as enum_Features_status,
  FeatureTransactionMap as FeatureTransactionMaps,
  ImageTarget as ImageTargets,
  ImageTargetStatus as enum_ImageTargets_status,
  ImageTargetType as enum_ImageTargets_type,
  Invite as Invites,
  Module as Modules,
  ModuleCompatibility as enum_Modules_compatibility,
  ModuleRepoVisibility as enum_Modules_repoVisibility,
  ModuleStatus as enum_Modules_status,
  ModuleTagMap as ModuleTagMaps,
  ModuleUser as ModuleUsers,
  NaeInfo as NaeInfos,
  NaeInfoPlatform as enum_NaeInfos_platform,
  NaePackagerBuild as NaePackagerBuilds,
  NaePackagerBuildBuildType as enum_NaePackagerBuilds_buildType,
  NaePackagerBuildStatus as enum_NaePackagerBuilds_status,
  NaePackagerChannel as NaePackagerChannels,
  NaePackagerChannelName as enum_NaePackagerChannels_name,
  NaePackagerVersionState as NaePackagerVersionStates,
  NaePackagerVersionStateName as enum_NaePackagerVersionStates_name,
  PlayerUser as PlayerUsers,
  PolicyViolation as PolicyViolations,
  PwaInfo as PwaInfos,
  ReferralCode as ReferralCodes,
  ReferralCodeRedemption as ReferralCodeRedemptions,
  ReferralCodeRedemptionSource as enum_ReferralCodeRedemptions_source,
  ReferralCodeRedemptionStatus as enum_ReferralCodeRedemptions_status,
  ReferralCodeReward as ReferralCodeRewards,
  ScheduledSubscription as ScheduledSubscriptions,
  ScheduledSubscriptionCollectionMethod as enum_ScheduledSubscriptions_collectionMethod,
  ScheduledSubscriptionScheduledStatus as enum_ScheduledSubscriptions_scheduledStatus,
  Transaction as Transactions,
  User as Users,
  UserAccount as User_Account,
  UserAccount as User_Accounts,
  UserAccountRole as enum_User_Accounts_role,
  UserAppPref as User_App_Pref,
  UserAppPref as User_App_Prefs,
  UserLoginMethodsProvider as enum_UserLoginMethods_provider,
  WayspotAnchor as WayspotAnchors,
}
