load("//bzl/capnproto:capnproto.bzl", "capnp_library")

package(default_visibility = ["//visibility:public"])

capnp_library(
    name = "info",
    srcs = [
        "info.capnp",
    ],
    deps = [
    ],
)
