load("//bzl/js:js.bzl", "js_library")

js_library(
    name = "generate-ts-from-cpp",
    srcs = [
        "generate-ts-from-cpp.ts",
    ],
    visibility = [
        "//visibility:public",
    ],
)
