load("//bzl/js:js.bzl", "js_library")

js_library(
    name = "apply",
    srcs = [
        "apply.js",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":constants",
        ":crop",
        ":image-data",
        ":types",
        ":unconify",
    ],
)

js_library(
    name = "types",
    srcs = [
        "types.ts",
    ],
)

js_library(
    name = "constants",
    srcs = [
        "constants.json",
    ],
)

js_library(
    name = "image-data",
    srcs = [
        "image-data.js",
    ],
)

js_library(
    name = "unconify",
    srcs = [
        "unconify.js",
    ],
)

js_library(
    name = "crop",
    srcs = [
        "crop.js",
    ],
)
