import React from 'react'
import type {Classes} from 'jss'
import {createUseStyles, Styles, ThemeProvider, useTheme as jssUseTheme} from 'react-jss'

import {
  blueberry, brandBlack, brandWhite, cherry, darkBlueberry, gray2, gray3, gray4, twoPercentCherry,
  brandHighlight, brandPurple, gray5, darkBlue, gray1, brandPurpleDark, moonlight, cherryLight,
  mango, mint, darkMint, eggshell, accessibleHighlight, darkOrange, almostBlack, gray6, csBlack,
  csGridLight, darkMango,
  mainBackgroundColor,
  darkBackground,
  bodySanSerif,
  headerSanSerif,
  blogBlue,
  postBoxShadow,
  cardShadowColor,
  lightBlue,
} from '../static/styles/settings'
import {hexColorWithAlpha} from '../../shared/colors'
import {useBrand8QaContext} from '../brand8/brand8-qa-context'
import {
  brand8Purple, brand8PurpleDarker, brand8Black, brand8Highlight, brand8PurpleDark,
  brand8Gray5, brand8Gray2,
} from './colors'
import {brand8BodyFontFamily, brand8HeadingFontFontFamily, brand8MonospaceFontFamily} from './fonts'
import {ICONS} from './standard-checkbox-field-svgs'

type UIThemeTokens =
  'fgMain' | 'fgMuted' | 'fgError' | 'fgBlue' | 'fgSuccess' | 'fgWarning' | 'fgDisabled' |
  'bgMain' | 'bgMuted' | 'bodyFontFamily' | 'headingFontFamily' | 'subHeadingFontFamily' |
  'toggleBackgroundDisabled' | 'toggleBackgroundEnabled' | 'toggleIndicator' |
  'controlInactive' | 'controlActive' | 'subtleBorder' | 'mainEditorPane' | 'mainDivider' |
  'sfcBackgroundDefault' | 'sfcBackgroundError' | 'sfcBorderDefault' | 'sfcBackdropFilter' |
  'sfcBackgroundFocus' | 'sfcDropdownChevronColor' | 'sfcDropdownChevronSize' |
  'sfcBorderFocus' | 'sfcBorderError' | 'sfcHighlight' | 'sfcDisabledBackground' |
  'sfcBorderRadius' | 'stfErrorTextMargin' | 'stfDisplay' | 'stfFlexDirection' | 'stfGap' |
  'sfcDisabledColor' | 'scrollbarTrackBackground' | 'scrollbarThumbColor' |
  'scrollbarThumbHoverColor' | 'descriptionBackground' | 'cloneIconBg' | 'cloneIconFilter' |
  'listBoxBg' | 'listBoxBorder' | 'listBoxShadow' |
  'listItemHoverBg' | 'listItemBorder' |
  'primaryBtnFg' | 'primaryBtnBg' | 'primaryBtnHoverBg' |
  'primaryBtnDisabledFg' | 'primaryBtnDisabledBg' | 'primaryBtnDisabledBgOpaque' |
  'primaryBtnBoxShadow' | 'primaryBtnContentFilter' |
  'fgPrimary' |
  'secondaryBtnBg' | 'secondaryBtnBoxShadow' | 'secondaryBtnContentFilter' |
  'secondaryBtnBorder' | 'secondaryBtnColor' | 'secondaryBtnHoverBg' | 'secondaryBtnDisabledFg' |
  'secondaryBtnDisabledBorder' |
  'tagBorderRadius' | 'tagFgDefault' | 'tagFgHover' | 'tagBorderRadiusSmall' |
  'tagBorderRadiusTiny' | 'tagBorder' | 'tagBg' | 'tagHoverBg' | 'tabHover' | 'tabActiveBg' |
  'tabDefault' | 'tabPaneBg' | 'tabBarBg' | 'textInputBorder' | 'tertiaryBtnFg' |
  'tertiaryBtnBg' | 'tertiaryBtnHoverBg' | 'tertiaryBtnDisabledFg' |
  'tertiaryBtnDisabledBg' |
  'roundedBtnFontWeight' | 'roundedBtnBorderRadius' | 'roundedBtnMediumHeight' |
  'roundedBtnMediumPadding' | 'roundedBtnSmallPadding' | 'roundedBtnSmallBorderRadius' |
  'roundedBtnTinyPadding' | 'roundedBtnTinyBorderRadius' |
  'createFormBorder' | 'createFormDivider' |
  'createFormBackground' | 'toolbarBtnColor' | 'toolbarBtnDisabledColor' |
  'toolbarBtnHoverBg' | 'toolbarBtnBgActive' | 'toolbarBtnFocusShadow' |
  'inputRequired' | 'inputBorder' | 'loaderPrimary' | 'loaderSecondary' |
  'loaderFontColor' | 'loaderFontSize' | 'loaderGap' |
  'semanticTooltipInverted' | 'modalFg' | 'modalBg' | 'modalContentBg' | 'modalContentBorder' |
  'modalBorder' | 'modalDimmerBg' | 'modalDimmerBackdropFilter' | 'modalBackdropFilter' |
  'modalIcon' | 'standardModalBg' | 'linkBtnFg' | 'linkBtnDisableFg' | 'bannerBgOpacityHex' |
  'bannerFgInfo' | 'bannerFgWarning' | 'bannerFgSuccess' | 'bannerFgDanger' |
  'bannerBgInfo' | 'bannerBgWarning' | 'bannerBgSuccess' | 'bannerBgDanger' |
  'bannerBorderInfo' | 'bannerBorderWarning' | 'bannerBorderSuccess' | 'bannerBorderDanger' |
  'bannerBorderRadius' | 'bannerCloseIconColor' |
  'textBtnHoverBg' |
  'publishModalTableBorder' | 'publishModalAccentBackground' | 'tabActiveLightBg' |
  'badgeSolidFg' | 'badgeMintColor' | 'badgeMintOutlinedColor' | 'badgeMangoSolidFgColor' |
  'badgeMangoColor' | 'badgeBlueColor' | 'badgeCherryColor' | 'badgePurpleColor' |
  'badgeGrayColor' | 'badgeBorderRadius' | 'badgeMangoOutlinedColor' | 'badgeCherryOutlinedColor' |
  'badgeGrayOutlinedColor' | 'badgeGraySolidFgColor' | 'badgePurpleOutlinedColor' |
  'badgeMintPastelFgColor' | 'badgeMangoPastelFgColor' | 'badgeBluePastelFgColor' |
  'badgeCherryPastelFgColor' | 'badgePurplePastelFgColor' | 'badgeGrayPastelFgColor' |
  'badgeMintPastelBgColor' | 'badgeMangoPastelBgColor' | 'badgeBluePastelBgColor' |
  'badgeCherryPastelBgColor' | 'badgePurplePastelBgColor' | 'badgeGrayPastelBgColor' |
  'tabDefaultLightBg' |
  'carouselArrowActive' | 'carouselArrowDisabled' | 'carouselArrowHover' |
  'codeEditorKeyword' | 'codeEditorString' | 'codeEditorBracket' |
  'codeEditorConstant' | 'codeEditorFunction' | 'codeEditorSecondaryBracket' |
  'codeEditorObjectKey' | 'tooltipInverted' | 'tooltipBg' |
  'stepperArrowBackground' | 'stepperBorder' | 'playbarBackground' |
  'playbarMarkerBg' | 'playbarMaskBg' | 'studioBgMain' | 'studioBtnHoverFg' | 'studioBtnActiveBg' |
  'studioPurpleBtnFg' | 'studioPurpleBtnBg' | 'studioWarningBtnFg' | 'studioWarningBtnBg' |
  'studioSuccessBtnFg' | 'studioSuccessBtnBg' |
  'studioBgBorder' | 'studioSectionBorder' | 'studioTreeHoverBg' | 'studioTreeGroupBg' |
  'studioTreeHidden' | 'studioBgOpaque' | 'studioBtnHoverBg' | 'studioPanelBtnBg' |
  'studioPanelBtnHoverBg' | 'studioGridCell' | 'studioGridSection' | 'studioSkyboxStart' |
  'studioSkyboxEnd' | 'studioDangerBtnFg' | 'studioDangerBtnBg' | 'studioAssetBorder' |
  'studioAssetBg' | 'iconBtnBorder' | 'toggleBtnOn' | 'modifiedColor' |
  'publishModalSidebarNav' | 'publishModalSidebarActiveBg' | 'publishModalBtnFg' |
  'publishModalTextBg' | 'teamRibbonBg' |
  'studioFullscreenBackground' |
  'publishModalText' | 'publishModalBg' | 'modalContainerBg' | 'overlayBg' | 'overlayFg' |
  'inputFieldBg' | 'creditTrackerFg' | 'buttonBgInactive' | 'publishModalBannerHoverBg' |
  'placeholderBackgroundColor' | 'placeholderBackgroundImage' |
  'fgBlog' | 'bgBlog' | 'blogBoxShadow' | 'blogHighlightBg' | 'blogSubtleBg' |
  'standardLabelColor' |
  'checkboxBg' | 'checkboxBorder' | 'checkboxBorderRadius' | 'checkboxDisplay' |
  'checkboxAlignment' | 'checkBoxSize' |
  'checkmarkBorder' | 'checkmarkBorderRadius' | 'checkboxHover' | 'checkmarkSize' |
  'checkmarkClipPath' | 'radioButtonBg' | 'standardRadioButtonIndicatorBorder' |
  'standardRadioButtonIndicatorBackground' | 'standardRadioButtonPseudoElementDisplay' |
  'standardRadioButtonIndicatorBorderChecked' | 'appCardHeaderFontFamily' |
  'appCardBorder' |'appCardDisabledBorder' | 'appCardShadowColor' | 'appCardBgColor' |
  'tableBorder' | 'tableHeadBg' | 'tableHeadFg' | 'recaptchaTheme' | 'navLogoColor' |
  'footerHeaderColor'| 'appCardCondensedWidth' | 'codeSearchResultBorderRadius' |
  'codeSearchResultAppCardPadding'

type UiTheme = Record<UIThemeTokens, any>

type UseStylesCreator = <C extends string = string, Props = unknown>(
  styles: Styles<C, Props, UiTheme> | ((theme: UiTheme) => Styles<C, Props, undefined>)
) => (data?: Props & {theme: UiTheme}) => Classes<C>

type UseTheme = () => UiTheme

const createThemedStyles: UseStylesCreator = createUseStyles
const useUiTheme: UseTheme = jssUseTheme

/* eslint-disable max-len, local-rules/hardcoded-copy */
const LightTheme: UiTheme = {
  fgMain: brandBlack,
  fgMuted: gray4,
  fgError: cherry,
  fgBlue: darkBlueberry,
  fgSuccess: darkMint,
  fgWarning: darkOrange,
  fgPrimary: brandPurple,
  fgDisabled: gray3,
  bgMain: mainBackgroundColor,
  bgMuted: 'transparent',
  mainDivider: hexColorWithAlpha(brand8Black, 0.2),
  bodyFontFamily: bodySanSerif,
  headingFontFamily: headerSanSerif,
  subHeadingFontFamily: headerSanSerif,
  checkboxBg: 'unset',
  checkboxHover: 'unset',
  checkboxBorder: 'unset',
  checkboxBorderRadius: '2px',
  checkboxDisplay: 'block',
  checkboxAlignment: 'unset',
  checkBoxSize: 'none',
  checkmarkSize: '16px',
  checkmarkBorder: `2px solid ${gray3}`,
  checkmarkBorderRadius: '2px',
  checkmarkClipPath: ICONS.checkmarkOld,
  controlInactive: gray3,
  controlActive: gray5,
  subtleBorder: gray2,
  mainEditorPane: brandWhite,
  listBoxBg: brandWhite,
  listBoxBorder: `1px solid ${gray2}`,
  listBoxShadow: `0px 0px 6px ${gray5}20`,
  listItemHoverBg: gray1,
  listItemBorder: 'none',
  sfcBackgroundDefault: brandWhite,
  sfcBackgroundFocus: 'default',
  sfcBackgroundError: twoPercentCherry,
  sfcBorderDefault: gray2,
  sfcBorderFocus: blueberry,
  sfcBorderError: cherry,
  sfcHighlight: gray3,
  sfcDisabledBackground: moonlight,
  sfcDisabledColor: gray3,
  sfcBackdropFilter: 'none',
  stfDisplay: 'unset',
  stfErrorTextMargin: 'none',
  stfFlexDirection: 'unset',
  stfGap: 'unset',
  standardLabelColor: brandBlack,
  toggleBackgroundEnabled: brandPurple,
  toggleBackgroundDisabled: gray2,
  toggleIndicator: brandWhite,
  scrollbarTrackBackground: hexColorWithAlpha('#000000', 0.1),
  scrollbarThumbColor: hexColorWithAlpha('#000000', 0.15),
  scrollbarThumbHoverColor: hexColorWithAlpha('#000000', 0.25),
  primaryBtnFg: brandWhite,
  primaryBtnBg: brandPurple,
  primaryBtnHoverBg: brandPurpleDark,
  primaryBtnDisabledFg: `${brandWhite}A6`,
  primaryBtnDisabledBg: `${brandPurple}33`,
  primaryBtnDisabledBgOpaque: hexColorWithAlpha(brandPurple, 0.2),
  primaryBtnBoxShadow: 'none',
  primaryBtnContentFilter: 'none',
  secondaryBtnBg: 'transparent',
  secondaryBtnBoxShadow: 'none',
  secondaryBtnContentFilter: 'none',
  secondaryBtnColor: brandPurple,
  secondaryBtnBorder: `1px solid ${brandPurple}`,
  secondaryBtnDisabledBorder: `1px solid ${gray3}`,
  secondaryBtnHoverBg: 'rgba(173, 80, 255, 0.05)',
  secondaryBtnDisabledFg: gray3,
  tertiaryBtnFg: brandBlack,
  tertiaryBtnBg: gray2,
  tertiaryBtnHoverBg: gray3,
  tertiaryBtnDisabledFg: gray3,
  tertiaryBtnDisabledBg: gray2,
  roundedBtnFontWeight: 600,
  roundedBtnBorderRadius: '6px',
  roundedBtnMediumHeight: '38px',
  roundedBtnMediumPadding: '9px 16px',
  roundedBtnSmallPadding: '6px 12px',
  roundedBtnSmallBorderRadius: '6px',
  roundedBtnTinyPadding: '4px 8px',
  roundedBtnTinyBorderRadius: '4px',
  descriptionBackground: gray2,
  tagBorderRadius: '2px',
  tagBorderRadiusSmall: '2px',
  tagBorderRadiusTiny: '2px',
  tagFgDefault: brandBlack,
  tagFgHover: brandBlack,
  tagBorder: 'none',
  tagBg: gray1,
  tagHoverBg: gray2,
  tabHover: brandBlack,
  tabActiveBg: moonlight,
  tabActiveLightBg: gray1,
  tabDefault: brandBlack,
  tabDefaultLightBg: gray4,
  tabPaneBg: gray1,
  tabBarBg: moonlight,
  teamRibbonBg: brandPurple,
  createFormBorder: `1px solid ${gray2}`,
  createFormBackground: brandWhite,
  createFormDivider: `1px solid ${gray2}`,
  toolbarBtnColor: gray4,
  toolbarBtnDisabledColor: gray2,
  toolbarBtnHoverBg: gray1,
  toolbarBtnBgActive: gray2,
  toolbarBtnFocusShadow: `0 0 0 2px ${gray4}`,
  inputRequired: cherry,
  inputBorder: gray2,
  inputFieldBg: brandWhite,
  badgeBorderRadius: '2px',
  badgeSolidFg: brandWhite,
  badgePurpleColor: brandHighlight,
  badgePurpleOutlinedColor: brandHighlight,
  badgePurplePastelFgColor: brandPurple,
  badgePurplePastelBgColor: hexColorWithAlpha(brandHighlight, 0.1),
  badgeBlueColor: lightBlue,
  badgeBluePastelFgColor: lightBlue,
  badgeBluePastelBgColor: hexColorWithAlpha(lightBlue, 0.1),
  badgeMangoColor: mango,
  badgeMangoOutlinedColor: mango,
  badgeMangoSolidFgColor: gray5,
  badgeMangoPastelFgColor: darkOrange,
  badgeMangoPastelBgColor: hexColorWithAlpha(mango, 0.33),
  badgeMintColor: darkMint,
  badgeMintOutlinedColor: darkMint,
  badgeMintPastelFgColor: darkMint,
  badgeMintPastelBgColor: hexColorWithAlpha(mint, 0.1),
  badgeCherryColor: cherry,
  badgeCherryOutlinedColor: cherry,
  badgeCherryPastelFgColor: cherry,
  badgeCherryPastelBgColor: hexColorWithAlpha(cherry, 0.1),
  badgeGrayColor: gray4,
  badgeGraySolidFgColor: gray1,
  badgeGrayOutlinedColor: gray4,
  badgeGrayPastelFgColor: gray4,
  badgeGrayPastelBgColor: hexColorWithAlpha(gray4, 0.15),
  semanticTooltipInverted: true,
  modalFg: brandBlack,
  modalBg: brandWhite,
  modalBorder: 'none',
  modalContentBg: eggshell,
  modalContentBorder: 'none',
  modalIcon: gray2,
  modalContainerBg: gray1,
  modalDimmerBg: hexColorWithAlpha(darkBlue, 0.2),
  modalDimmerBackdropFilter: 'blur(10px)',
  modalBackdropFilter: 'none',
  standardModalBg: brandWhite,
  linkBtnFg: brandPurple,
  linkBtnDisableFg: gray3,
  textBtnHoverBg: hexColorWithAlpha(gray2, 0.35),
  // TODO (tri): remove these when 8w Buttons are implemented
  cloneIconBg: gray1,
  cloneIconFilter: 'none',
  textInputBorder: `1px solid ${gray2}`,
  loaderFontColor: 'inherit',
  loaderFontSize: '1rem',
  loaderGap: '6px',
  loaderPrimary: gray4,
  loaderSecondary: gray2,
  bannerFgDanger: cherry,
  bannerFgInfo: darkBlueberry,
  bannerFgSuccess: darkMint,
  bannerFgWarning: darkOrange,
  bannerBgOpacityHex: '05',
  bannerBgInfo: hexColorWithAlpha(blueberry, 0.02),
  bannerBgWarning: hexColorWithAlpha(mango, 0.02),
  bannerBgSuccess: hexColorWithAlpha(mint, 0.02),
  bannerBgDanger: hexColorWithAlpha(cherryLight, 0.02),
  bannerBorderInfo: `1px solid ${blueberry}`,
  bannerBorderWarning: `1px solid ${mango}`,
  bannerBorderSuccess: `1px solid ${mint}`,
  bannerBorderDanger: `1px solid ${cherryLight}`,
  bannerBorderRadius: 'none',
  bannerCloseIconColor: gray4,
  publishModalTableBorder: `1px solid ${gray1}`,
  publishModalAccentBackground: moonlight,
  publishModalBg: moonlight,
  publishModalSidebarNav: brandWhite,
  publishModalText: gray5,
  publishModalSidebarActiveBg: `${gray2}80`,
  publishModalBtnFg: brandBlack,
  publishModalTextBg: brandWhite,
  publishModalBannerHoverBg: hexColorWithAlpha(gray2, 0.5),
  carouselArrowActive: gray4,
  carouselArrowDisabled: gray1,
  carouselArrowHover: gray5,
  codeEditorKeyword: '#9472cf',
  codeEditorString: '#7dad45',
  codeEditorBracket: '#0431fa',
  codeEditorConstant: '#4876d6',
  codeEditorFunction: '#9472cf',
  codeEditorSecondaryBracket: '#319331',
  codeEditorObjectKey: '#7982b3',
  sfcBorderRadius: '4px',
  sfcDropdownChevronColor: gray4,
  sfcDropdownChevronSize: '0.5rem',
  tooltipInverted: true,
  tooltipBg: moonlight,
  stepperArrowBackground: gray2,
  stepperBorder: gray2,
  playbarBackground: gray3,
  playbarMarkerBg: brandPurple,
  playbarMaskBg: hexColorWithAlpha(brandPurple, 0.33),
  studioBgMain: hexColorWithAlpha(moonlight, 0.85),
  studioBgOpaque: moonlight,
  studioFullscreenBackground: gray2,
  studioBtnHoverFg: brandBlack,
  studioBtnHoverBg: gray2,
  studioBtnActiveBg: gray3,
  studioPurpleBtnFg: brandPurple,
  studioPurpleBtnBg: hexColorWithAlpha(brandHighlight, 0.25),
  studioWarningBtnFg: brandBlack,
  studioWarningBtnBg: hexColorWithAlpha(mango, 0.25),
  studioDangerBtnFg: cherry,
  studioDangerBtnBg: hexColorWithAlpha(cherry, 0.25),
  studioSuccessBtnFg: brandBlack,
  studioSuccessBtnBg: hexColorWithAlpha(mint, 0.25),
  studioBgBorder: `1px solid ${gray3}`,
  studioSectionBorder: `1px solid ${gray3}`,
  studioTreeHoverBg: hexColorWithAlpha(gray5, 0.1),
  studioTreeGroupBg: hexColorWithAlpha(gray5, 0.07),
  studioTreeHidden: gray4,
  studioPanelBtnBg: gray3,
  studioPanelBtnHoverBg: gray4,
  studioGridCell: csGridLight,
  studioGridSection: gray4,
  studioSkyboxStart: gray1,
  studioSkyboxEnd: gray3,
  studioAssetBorder: gray3,
  studioAssetBg: brandWhite,
  iconBtnBorder: `1px solid ${gray2}`,
  toggleBtnOn: brandHighlight,
  modifiedColor: darkMango,
  // When you want to overlay text on top of a background image
  overlayBg: hexColorWithAlpha(gray5, 0.9),
  overlayFg: brandWhite,
  creditTrackerFg: gray4,
  buttonBgInactive: gray1,
  placeholderBackgroundColor: mainBackgroundColor,
  placeholderBackgroundImage: `linear-gradient(to right, ${hexColorWithAlpha(brandBlack, 0.08)} 0, ${hexColorWithAlpha(brandBlack, 0.15)} 15%, ${hexColorWithAlpha(brandBlack, 0.08)} 30%)`,
  fgBlog: gray6,
  bgBlog: blogBlue,
  blogBoxShadow: postBoxShadow,
  blogHighlightBg: brandPurple,
  blogSubtleBg: gray5,
  radioButtonBg: 'transparent',
  standardRadioButtonIndicatorBorder: `2px solid ${gray3}`,
  standardRadioButtonIndicatorBorderChecked: `5px solid ${gray5}`,
  standardRadioButtonIndicatorBackground: 'inherit',
  standardRadioButtonPseudoElementDisplay: 'none',
  appCardHeaderFontFamily: bodySanSerif,
  appCardBorder: 'none',
  appCardDisabledBorder: `1px solid ${gray1}`,
  appCardShadowColor: cardShadowColor,
  appCardBgColor: brandWhite,
  tableBorder: `1px solid ${brandBlack}`,
  tableHeadBg: gray1,
  tableHeadFg: 'inherit',
  recaptchaTheme: 'light',
  navLogoColor: 'purple',
  footerHeaderColor: brandBlack,
  appCardCondensedWidth: '25em',
  codeSearchResultBorderRadius: '0',
  codeSearchResultAppCardPadding: 'auto',
}
/* eslint-enable max-len, local-rules/hardcoded-copy */

/* eslint-disable max-len, local-rules/hardcoded-copy */
const DarkTheme: UiTheme = {
  fgMain: brandWhite,
  fgMuted: gray3,
  fgBlue: blueberry,
  fgError: cherryLight,
  fgSuccess: mint,
  fgWarning: mango,
  fgPrimary: accessibleHighlight,
  fgDisabled: hexColorWithAlpha(gray4, 0.6),
  bgMain: brand8Black,
  bgMuted: 'transparent',
  mainDivider: hexColorWithAlpha(brandWhite, 0.2),
  bodyFontFamily: bodySanSerif,
  headingFontFamily: headerSanSerif,
  subHeadingFontFamily: headerSanSerif,
  checkboxBg: 'unset',
  checkboxHover: 'unset',
  checkboxBorder: 'unset',
  checkboxBorderRadius: '2px',
  checkboxDisplay: 'block',
  checkboxAlignment: 'unset',
  checkmarkSize: '16px',
  checkBoxSize: 'none',
  checkmarkBorder: `2px solid ${gray3}`,
  checkmarkBorderRadius: '2px',
  checkmarkClipPath: ICONS.checkmarkOld,
  controlInactive: gray3,
  controlActive: brandWhite,
  subtleBorder: gray5,
  mainEditorPane: darkBlue,
  listBoxBg: brandBlack,
  listBoxBorder: `1px solid ${gray5}`,
  listBoxShadow: 'none',
  listItemHoverBg: `${gray4}32`,
  listItemBorder: `1px solid ${gray5}`,
  sfcBackgroundDefault: brandBlack,
  sfcBackgroundFocus: 'default',
  sfcBackgroundError: brandBlack,
  sfcBorderDefault: 'transparent',
  sfcBorderFocus: blueberry,
  sfcBorderError: cherry,
  sfcHighlight: hexColorWithAlpha(gray4, 0.999),
  sfcDisabledBackground: brandBlack,
  sfcDisabledColor: gray4,
  sfcBackdropFilter: 'none',
  stfDisplay: 'unset',
  stfErrorTextMargin: 'none',
  stfFlexDirection: 'unset',
  stfGap: 'unset',
  standardLabelColor: brandWhite,
  toggleBackgroundEnabled: brandHighlight,
  toggleBackgroundDisabled: gray4,
  toggleIndicator: brandWhite,
  teamRibbonBg: brandHighlight,
  scrollbarTrackBackground: hexColorWithAlpha('#000000', 0.2),
  scrollbarThumbColor: hexColorWithAlpha(brandWhite, 0.15),
  scrollbarThumbHoverColor: hexColorWithAlpha(brandWhite, 0.25),
  primaryBtnFg: brandWhite,
  primaryBtnBg: brandHighlight,
  primaryBtnHoverBg: brandPurple,
  primaryBtnDisabledFg: gray4,
  primaryBtnDisabledBg: '#684a99',
  primaryBtnDisabledBgOpaque: hexColorWithAlpha(brandHighlight, 0.33),
  primaryBtnBoxShadow: 'none',
  primaryBtnContentFilter: 'none',
  secondaryBtnBg: 'transparent',
  secondaryBtnBoxShadow: 'none',
  secondaryBtnContentFilter: 'none',
  secondaryBtnColor: brandWhite,
  secondaryBtnBorder: `1px solid ${gray2}`,
  secondaryBtnDisabledBorder: `1px solid ${gray4}`,
  secondaryBtnHoverBg: 'rgba(128, 131, 162, 0.35)',
  secondaryBtnDisabledFg: gray4,
  tertiaryBtnFg: brandBlack,
  tertiaryBtnBg: gray2,
  tertiaryBtnHoverBg: gray3,
  tertiaryBtnDisabledFg: `${gray4}99`,
  tertiaryBtnDisabledBg: '#4f506f',
  roundedBtnFontWeight: 600,
  roundedBtnBorderRadius: '6px',
  roundedBtnMediumHeight: '38px',
  roundedBtnMediumPadding: '9px 16px',
  roundedBtnSmallPadding: '6px 12px',
  roundedBtnSmallBorderRadius: '6px',
  roundedBtnTinyPadding: '4px 8px',
  roundedBtnTinyBorderRadius: '4px',
  descriptionBackground: brandBlack,
  tagFgDefault: gray3,
  tagFgHover: brandWhite,
  tagBorderRadius: '2px',
  tagBorderRadiusSmall: '2px',
  tagBorderRadiusTiny: '2px',
  tagBorder: `1px solid ${gray4}66`,
  tagBg: 'transparent',
  tagHoverBg: `${gray4}40`,
  tabHover: brandWhite,
  tabActiveBg: gray5,
  tabActiveLightBg: gray5,
  tabDefault: gray3,
  tabDefaultLightBg: gray4,
  tabPaneBg: brandBlack,
  tabBarBg: almostBlack,
  createFormBorder: 'none',
  createFormBackground: brandBlack,
  createFormDivider: `1px solid ${gray5}`,
  toolbarBtnColor: brandWhite,
  toolbarBtnDisabledColor: gray4,
  toolbarBtnHoverBg: gray3,
  toolbarBtnBgActive: gray2,
  toolbarBtnFocusShadow: `0 0 0 2px ${gray4}`,
  inputRequired: cherryLight,
  inputBorder: darkBlue,
  inputFieldBg: darkBlue,
  badgeBorderRadius: '2px',
  badgeSolidFg: brandWhite,
  badgePurpleColor: brandHighlight,
  badgePurpleOutlinedColor: brandHighlight,
  badgePurplePastelFgColor: accessibleHighlight,
  badgePurplePastelBgColor: hexColorWithAlpha(brandPurple, 0.33),
  badgeBlueColor: lightBlue,
  badgeBluePastelFgColor: lightBlue,
  badgeBluePastelBgColor: hexColorWithAlpha(lightBlue, 0.33),
  badgeMangoSolidFgColor: gray5,
  badgeMangoPastelFgColor: mango,
  badgeMangoPastelBgColor: hexColorWithAlpha(mango, 0.33),
  badgeMangoColor: mango,
  badgeMangoOutlinedColor: mango,
  badgeMintColor: darkMint,
  badgeMintOutlinedColor: mint,
  badgeMintPastelFgColor: mint,
  badgeMintPastelBgColor: hexColorWithAlpha(mint, 0.33),
  badgeCherryColor: cherry,
  badgeCherryOutlinedColor: cherry,
  badgeCherryPastelFgColor: cherryLight,
  badgeCherryPastelBgColor: hexColorWithAlpha(cherry, 0.33),
  badgeGrayColor: gray4,
  badgeGraySolidFgColor: gray1,
  badgeGrayOutlinedColor: gray4,
  badgeGrayPastelFgColor: gray3,
  badgeGrayPastelBgColor: hexColorWithAlpha(gray4, 0.33),
  semanticTooltipInverted: false,
  modalFg: brandWhite,
  modalBg: csBlack,
  modalBorder: 'none',
  modalContentBg: darkBlue,
  modalContentBorder: 'none',
  modalIcon: hexColorWithAlpha(moonlight, 0.2),
  modalContainerBg: brandBlack,
  modalBackdropFilter: 'none',
  standardModalBg: csBlack,
  modalDimmerBg: hexColorWithAlpha(darkBlue, 0.2),
  modalDimmerBackdropFilter: 'blur(10px)',
  linkBtnFg: brandWhite,
  linkBtnDisableFg: gray4,
  textBtnHoverBg: hexColorWithAlpha(gray5, 0.35),
  // TODO (tri): remove these when 8w Buttons are implemented
  cloneIconBg: 'none',
  cloneIconFilter: 'invert(0.8) saturate(0) brightness(2)',
  textInputBorder: 'none',
  loaderFontColor: 'inherit',
  loaderFontSize: '1rem',
  loaderGap: '6px',
  loaderPrimary: brandWhite,
  loaderSecondary: gray4,
  bannerFgInfo: blueberry,
  bannerFgDanger: cherryLight,
  bannerFgSuccess: mint,
  bannerFgWarning: mango,
  bannerBgOpacityHex: '0D',
  bannerBgInfo: hexColorWithAlpha(blueberry, 0.05),
  bannerBgWarning: hexColorWithAlpha(mango, 0.05),
  bannerBgSuccess: hexColorWithAlpha(mint, 0.05),
  bannerBgDanger: hexColorWithAlpha(cherryLight, 0.05),
  bannerBorderInfo: `1px solid ${blueberry}`,
  bannerBorderWarning: `1px solid ${mango}`,
  bannerBorderSuccess: `1px solid ${mint}`,
  bannerBorderDanger: `1px solid ${cherryLight}`,
  bannerBorderRadius: 'none',
  bannerCloseIconColor: gray4,
  publishModalTableBorder: `1px solid ${gray4}`,
  publishModalAccentBackground: darkBlue,
  publishModalBg: csBlack,
  publishModalSidebarNav: darkBlue,
  publishModalText: gray3,
  publishModalSidebarActiveBg: gray5,
  publishModalBtnFg: brandWhite,
  publishModalTextBg: darkBlue,
  publishModalBannerHoverBg: hexColorWithAlpha(gray5, 0.5),
  carouselArrowActive: gray3,
  carouselArrowDisabled: gray6,
  carouselArrowHover: gray1,
  codeEditorKeyword: '#aa97ff',
  codeEditorString: '#c8e495',
  codeEditorBracket: '#ffd700',
  codeEditorConstant: '#a9d4ff',
  codeEditorFunction: '#d4b9ff',
  codeEditorSecondaryBracket: '#da70d6',
  codeEditorObjectKey: '#bfc7d5',
  sfcBorderRadius: '4px',
  sfcDropdownChevronColor: gray3,
  sfcDropdownChevronSize: '0.5rem',
  tooltipInverted: false,
  tooltipBg: brandBlack,
  stepperArrowBackground: gray5,
  stepperBorder: 'transparent',
  playbarBackground: gray5,
  playbarMarkerBg: brandHighlight,
  playbarMaskBg: hexColorWithAlpha(brandHighlight, 0.33),
  studioBgMain: hexColorWithAlpha(csBlack, 0.85),
  studioBgOpaque: csBlack,
  studioFullscreenBackground: csBlack,
  studioBtnHoverFg: brandWhite,
  studioBtnHoverBg: gray5,
  studioBtnActiveBg: gray5,
  studioPurpleBtnFg: accessibleHighlight,
  studioPurpleBtnBg: hexColorWithAlpha(brandHighlight, 0.2),
  studioWarningBtnFg: brandWhite,
  studioWarningBtnBg: hexColorWithAlpha(mango, 0.2),
  studioDangerBtnFg: cherry,
  studioDangerBtnBg: hexColorWithAlpha(cherry, 0.25),
  studioSuccessBtnFg: mint,
  studioSuccessBtnBg: hexColorWithAlpha(mint, 0.2),
  studioBgBorder: 'none',
  studioSectionBorder: `1px solid ${gray5}`,
  studioTreeHoverBg: hexColorWithAlpha(gray5, 0.5),
  studioTreeGroupBg: hexColorWithAlpha(gray5, 0.35),
  studioTreeHidden: gray4,
  studioPanelBtnBg: gray5,
  studioPanelBtnHoverBg: gray4,
  studioGridCell: gray6,
  studioGridSection: gray5,
  studioSkyboxStart: gray5,
  studioSkyboxEnd: csBlack,
  studioAssetBorder: gray5,
  studioAssetBg: darkBlue,
  iconBtnBorder: 'none',
  toggleBtnOn: brandHighlight,
  modifiedColor: mango,
  overlayBg: hexColorWithAlpha(gray5, 0.9),
  overlayFg: brandWhite,
  creditTrackerFg: blueberry,
  buttonBgInactive: gray5,
  placeholderBackgroundColor: darkBackground,
  placeholderBackgroundImage: `linear-gradient(to right, ${hexColorWithAlpha(brandWhite, 0.08)} 0, ${hexColorWithAlpha(brandWhite, 0.15)} 15%, ${hexColorWithAlpha(brandWhite, 0.08)} 30%)`,
  fgBlog: gray6,
  bgBlog: blogBlue,
  blogBoxShadow: postBoxShadow,
  blogHighlightBg: brandPurple,
  blogSubtleBg: gray5,
  radioButtonBg: 'transparent',
  standardRadioButtonIndicatorBorder: `2px solid ${gray3}`,
  standardRadioButtonIndicatorBorderChecked: `5px solid ${brandWhite}`,
  standardRadioButtonIndicatorBackground: 'inherit',
  standardRadioButtonPseudoElementDisplay: 'none',
  appCardHeaderFontFamily: bodySanSerif,
  appCardBorder: `1px solid ${hexColorWithAlpha(brandWhite, 0.1)}`,
  appCardDisabledBorder: hexColorWithAlpha(brandWhite, 0.5),
  appCardShadowColor: hexColorWithAlpha(brandWhite, 0.15),
  appCardBgColor: hexColorWithAlpha(brandWhite, 0.1),
  tableBorder: `1px solid ${brandWhite}`,
  tableHeadBg: hexColorWithAlpha(brandWhite, 0.1),
  tableHeadFg: 'inherit',
  recaptchaTheme: 'dark',
  navLogoColor: 'white',
  footerHeaderColor: brandWhite,
  appCardCondensedWidth: '25em',
  codeSearchResultBorderRadius: '0',
  codeSearchResultAppCardPadding: 'auto',

}
/* eslint-enable max-len, local-rules/hardcoded-copy */

/* eslint-disable max-len, local-rules/hardcoded-copy */
const Brand8DarkTheme: UiTheme = {
  ...DarkTheme,
  tagBorder: `1px solid ${hexColorWithAlpha(brandWhite, 0.05)}`,
  tagBg: hexColorWithAlpha(brandWhite, 0.1),
  tagHoverBg: hexColorWithAlpha(brandWhite, 0.2),
  tagFgDefault: hexColorWithAlpha(brandWhite, 0.5),
  tagFgHover: brandWhite,
  tagBorderRadius: '8px',
  tagBorderRadiusSmall: '6px',
  tagBorderRadiusTiny: '4px',
  textBtnHoverBg: hexColorWithAlpha(gray4, 0.35),
  teamRibbonBg: brand8Highlight,
  fgMain: brandWhite,
  bgMain: brand8Black,
  bodyFontFamily: brand8BodyFontFamily,
  headingFontFamily: brand8HeadingFontFontFamily,
  subHeadingFontFamily: brand8MonospaceFontFamily,
  fgMuted: hexColorWithAlpha(brandWhite, 0.5),
  bgMuted: hexColorWithAlpha(brandWhite, 0.1),
  fgError: cherryLight,
  fgBlue: blueberry,
  fgSuccess: mint,
  fgWarning: mango,
  fgPrimary: brand8Highlight,
  mainDivider: hexColorWithAlpha(brandWhite, 0.2),
  bannerFgInfo: brandWhite,
  bannerFgDanger: brandWhite,
  bannerFgSuccess: brandWhite,
  bannerFgWarning: brandWhite,
  bannerBgInfo: hexColorWithAlpha(blueberry, 0.15),
  bannerBgWarning: hexColorWithAlpha(mango, 0.15),
  bannerBgSuccess: hexColorWithAlpha(mint, 0.15),
  bannerBgDanger: hexColorWithAlpha(cherry, 0.2),
  bannerBorderInfo: 'none',
  bannerBorderWarning: 'none',
  bannerBorderSuccess: 'none',
  bannerBorderDanger: 'none',
  bannerBorderRadius: '10px',
  bannerCloseIconColor: brandWhite,
  checkboxBg: hexColorWithAlpha(brandWhite, 0.1),
  checkboxHover: hexColorWithAlpha(brandWhite, 0.2),
  checkboxBorder: `2px solid ${hexColorWithAlpha(brandWhite, 0.2)}`,
  checkboxBorderRadius: '4px',
  checkboxDisplay: 'flex',
  checkboxAlignment: 'center',
  checkBoxSize: '16px',
  checkmarkBorder: 'none',
  checkmarkClipPath: ICONS.checkmarkBrand8,
  checkmarkSize: '14px',
  checkmarkBorderRadius: 'none',
  codeSearchResultAppCardPadding: '8px',
  codeSearchResultBorderRadius: '8px',
  controlActive: brandWhite,
  controlInactive: hexColorWithAlpha(brandWhite, 0.2),
  linkBtnDisableFg: hexColorWithAlpha(gray4, 0.6),
  linkBtnFg: brandWhite,
  listBoxBorder: `1px solid ${hexColorWithAlpha(brandWhite, 0.2)}`,
  loaderFontColor: brandWhite,
  loaderFontSize: '0.85rem',
  loaderGap: '8px',
  loaderPrimary: hexColorWithAlpha(brandWhite, 0.5),
  loaderSecondary: hexColorWithAlpha(brandWhite, 0.2),
  modalBackdropFilter: 'blur(50px)',
  modalBg: brand8Black,
  standardModalBg: hexColorWithAlpha(brand8Black, 0.50),
  modalBorder: `1px solid ${hexColorWithAlpha(brandWhite, 0.1)}`,
  modalContentBg: hexColorWithAlpha(brandWhite, 0.1),
  modalContentBorder: `1px solid ${hexColorWithAlpha(brandWhite, 0.1)}`,
  modalDimmerBg: hexColorWithAlpha(brand8Black, 0.8),
  modalDimmerBackdropFilter: 'none',
  primaryBtnFg: brandWhite,
  primaryBtnBg: `radial-gradient(217.26% 611.25% at 127.54% 430%, rgba(118, 17, 182, 0) 0%, ${brand8Purple} 71.63%, rgba(255, 230, 185, 0.5) 100%), ${brand8PurpleDarker}`,
  primaryBtnHoverBg: `radial-gradient(228.22% 616.67% at 73.71% 435.42%, rgba(255, 255, 255, 0.05) 15.38%, ${brand8Purple} 50.96%, #FFE6B9 100%), ${brand8PurpleDarker}`,
  primaryBtnDisabledFg: `${hexColorWithAlpha(brandWhite, 0.5)}`,
  primaryBtnDisabledBg: `radial-gradient(217.26% 611.25% at 127.54% 430%, ${hexColorWithAlpha(brand8Purple, 0)} 38.46%, ${hexColorWithAlpha(brand8Purple, 0.2)} 69.23%, rgba(255, 230, 185, 0.2) 100%), ${hexColorWithAlpha(brand8Purple, 0.2)}`,
  primaryBtnDisabledBgOpaque: hexColorWithAlpha(brand8Purple, 0.2),
  primaryBtnBoxShadow: '0px 1px 4px rgba(0, 0, 0, 0.1), inset 0px 2px 3px rgba(255, 255, 255, 0.36)',
  primaryBtnContentFilter: `drop-shadow(0px 1px 1px ${brandPurple})`,
  radioButtonBg: brand8Black,
  roundedBtnFontWeight: 400,
  roundedBtnBorderRadius: '10px',
  roundedBtnMediumHeight: '40px',
  roundedBtnMediumPadding: '12px 12px',
  roundedBtnSmallPadding: '6px 10px',
  roundedBtnSmallBorderRadius: '8px',
  roundedBtnTinyPadding: '4px 8px',
  roundedBtnTinyBorderRadius: '6px',
  secondaryBtnBorder: 'none',
  secondaryBtnDisabledBorder: 'none',
  secondaryBtnBg: `${hexColorWithAlpha(brandWhite, 0.2)}`,
  secondaryBtnColor: brandWhite,
  secondaryBtnHoverBg: `${hexColorWithAlpha(brandWhite, 0.3)}`,
  secondaryBtnDisabledFg: `${hexColorWithAlpha(brandWhite, 0.2)}`,
  secondaryBtnBoxShadow: `inset 0px 1px 2px ${hexColorWithAlpha(brandWhite, 0.25)}`,
  secondaryBtnContentFilter: 'drop-shadow(0px 0px 2px rgba(0, 0, 0, 0.75))',
  sfcBackgroundDefault: hexColorWithAlpha(brandWhite, 0.1),
  sfcBackgroundFocus: hexColorWithAlpha(brandWhite, 0.2),
  sfcBackgroundError: hexColorWithAlpha(brandWhite, 0.1),
  sfcBorderDefault: hexColorWithAlpha(brandWhite, 0.05),
  sfcDisabledBackground: hexColorWithAlpha(brandWhite, 0.1),
  sfcDisabledColor: hexColorWithAlpha(brandWhite, 0.5),
  sfcBackdropFilter: 'blur(20px)',
  sfcBorderRadius: '8px',
  sfcDropdownChevronColor: brandWhite,
  sfcDropdownChevronSize: '5px',
  standardRadioButtonIndicatorBackground: hexColorWithAlpha(brandWhite, 0.1),
  standardRadioButtonIndicatorBorder: `1px solid ${hexColorWithAlpha(brandWhite, 0.2)}`,
  standardRadioButtonIndicatorBorderChecked: `1px solid ${hexColorWithAlpha(brandWhite, 0.2)}`,
  standardRadioButtonPseudoElementDisplay: 'block',
  stfDisplay: 'flex',
  stfErrorTextMargin: '0.25em',
  stfFlexDirection: 'column',
  stfGap: '0.5em',
  standardLabelColor: hexColorWithAlpha(brandWhite, 0.5),
  tableBorder: `1px solid ${brand8Gray5}`,
  tableHeadBg: hexColorWithAlpha(brandWhite, 0.1),
  tableHeadFg: hexColorWithAlpha(brandWhite, 0.5),
  placeholderBackgroundColor: brand8Black,
  placeholderBackgroundImage: `linear-gradient(to right, ${hexColorWithAlpha(brandWhite, 0.08)} 0, ${hexColorWithAlpha(brandWhite, 0.15)} 15%, ${hexColorWithAlpha(brandWhite, 0.08)} 30%)`,
  fgBlog: hexColorWithAlpha(brandWhite, 0.75),
  bgBlog: hexColorWithAlpha(brandWhite, 0.2),
  blogBoxShadow: `inset 0px 1px 2px ${hexColorWithAlpha(brandWhite, 0.25)}`,
  blogHighlightBg: brand8Purple,
  blogSubtleBg: hexColorWithAlpha(brandWhite, 0.5),
  appCardHeaderFontFamily: brand8MonospaceFontFamily,
  appCardCondensedWidth: '100%',
  appCardBorder: `1px solid ${hexColorWithAlpha(brandWhite, 0.1)}`,
  appCardDisabledBorder: hexColorWithAlpha(brandWhite, 0.5),
  appCardShadowColor: hexColorWithAlpha(brandWhite, 0.15),
  appCardBgColor: hexColorWithAlpha(brandWhite, 0.1),
  badgeBorderRadius: '4px',
  badgeSolidFg: brandWhite,
  badgePurpleColor: brand8Purple,
  badgePurpleOutlinedColor: brand8Highlight,
  badgePurplePastelFgColor: brand8Highlight,
  badgePurplePastelBgColor: hexColorWithAlpha(brand8Purple, 0.33),
  badgeBlueColor: blueberry,
  badgeBluePastelFgColor: blueberry,
  badgeBluePastelBgColor: hexColorWithAlpha(blueberry, 0.33),
  badgeMangoColor: mango,
  badgeMangoOutlinedColor: mango,
  badgeMangoSolidFgColor: brand8Black,
  badgeMangoPastelFgColor: mango,
  badgeMangoPastelBgColor: hexColorWithAlpha(mango, 0.33),
  badgeMintColor: darkMint,
  badgeMintOutlinedColor: mint,
  badgeMintPastelFgColor: mint,
  badgeMintPastelBgColor: hexColorWithAlpha(mint, 0.33),
  badgeCherryColor: cherryLight,
  badgeCherryOutlinedColor: cherryLight,
  badgeCherryPastelFgColor: cherryLight,
  badgeCherryPastelBgColor: hexColorWithAlpha(cherry, 0.33),
  badgeGrayColor: hexColorWithAlpha(brandWhite, 0.2),
  badgeGraySolidFgColor: hexColorWithAlpha(brandWhite, 0.5),
  badgeGrayOutlinedColor: hexColorWithAlpha(brandWhite, 0.5),
  badgeGrayPastelFgColor: hexColorWithAlpha(brandWhite, 0.5),
  badgeGrayPastelBgColor: hexColorWithAlpha(brandWhite, 0.15),
  recaptchaTheme: 'dark',
  navLogoColor: 'white',
  footerHeaderColor: hexColorWithAlpha(brandWhite, 0.3),

  // TODO(alvin): Overwrite theme attributes with new ones.
}
/* eslint-enable max-len */

/* eslint-disable max-len */
const Brand8LightTheme: UiTheme = {
  ...LightTheme,
  tagBorder: `1px solid ${hexColorWithAlpha(brand8Black, 0.05)}`,
  tagBg: hexColorWithAlpha(brand8Black, 0.02),
  tagHoverBg: hexColorWithAlpha(brand8Black, 0.05),
  tagFgDefault: hexColorWithAlpha(brand8Black, 0.5),
  tagFgHover: brand8Black,
  tagBorderRadius: '8px',
  tagBorderRadiusSmall: '6px',
  tagBorderRadiusTiny: '4px',
  textBtnHoverBg: hexColorWithAlpha(brandPurple, 0.1),
  teamRibbonBg: brand8Purple,
  fgMain: brand8Black,
  bgMain: brandWhite,
  bodyFontFamily: brand8BodyFontFamily,
  headingFontFamily: brand8HeadingFontFontFamily,
  subHeadingFontFamily: brand8MonospaceFontFamily,
  bgMuted: hexColorWithAlpha(brand8Black, 0.2),
  fgMuted: hexColorWithAlpha(brand8Black, 0.5),
  fgError: cherry,
  fgBlue: darkBlueberry,
  fgSuccess: darkMint,
  fgWarning: darkOrange,
  fgPrimary: brand8Purple,
  mainDivider: hexColorWithAlpha(brand8Black, 0.2),
  bannerFgInfo: brand8Black,
  bannerFgDanger: brand8Black,
  bannerFgSuccess: brand8Black,
  bannerFgWarning: brand8Black,
  bannerBgInfo: hexColorWithAlpha(blueberry, 0.1),
  bannerBgWarning: hexColorWithAlpha(mango, 0.1),
  bannerBgSuccess: hexColorWithAlpha(mint, 0.1),
  bannerBgDanger: hexColorWithAlpha(cherry, 0.15),
  bannerBorderInfo: 'none',
  bannerBorderWarning: 'none',
  bannerBorderSuccess: 'none',
  bannerBorderDanger: 'none',
  bannerBorderRadius: '10px',
  bannerCloseIconColor: hexColorWithAlpha(brand8Black, 0.5),
  checkboxBg: hexColorWithAlpha(brand8Black, 0.02),
  checkboxBorder: `2px solid ${hexColorWithAlpha(brand8Black, 0.2)}`,
  checkboxBorderRadius: '4px',
  checkboxDisplay: 'flex',
  checkboxAlignment: 'center',
  checkBoxSize: '16px',
  checkboxHover: hexColorWithAlpha(brand8Black, 0.1),
  checkmarkBorder: 'none',
  checkmarkBorderRadius: 'none',
  checkmarkClipPath: ICONS.checkmarkBrand8,
  checkmarkSize: '14px',
  codeSearchResultAppCardPadding: '8px',
  codeSearchResultBorderRadius: '8px',
  controlActive: brand8Black,
  linkBtnDisableFg: gray3,
  linkBtnFg: brandPurple,
  listBoxBorder: `1px solid ${hexColorWithAlpha(brandWhite, 0.1)}`,
  loaderFontColor: brand8Black,
  loaderFontSize: '0.85rem',
  loaderGap: '8px',
  loaderPrimary: hexColorWithAlpha(brand8Black, 0.5),
  loaderSecondary: hexColorWithAlpha(brand8Black, 0.2),
  modalBackdropFilter: 'blur(50px)',
  modalBg: brandWhite,
  standardModalBg: hexColorWithAlpha(brandWhite, 0.75),
  modalBorder: `1px solid ${hexColorWithAlpha(brand8Black, 0.05)}`,
  modalContentBg: hexColorWithAlpha(brand8Black, 0.02),
  modalContentBorder: `1px solid ${hexColorWithAlpha(brand8Black, 0.05)}`,
  modalDimmerBg: hexColorWithAlpha(brandWhite, 0.8),
  modalDimmerBackdropFilter: 'none',
  primaryBtnFg: brandWhite,
  primaryBtnBg: `radial-gradient(217.26% 611.25% at 127.54% 430%, rgba(118, 17, 182, 0) 0%, ${brand8Purple} 71.63%, rgba(255, 230, 185, 0.5) 100%), ${brand8PurpleDarker}`,
  primaryBtnHoverBg: `radial-gradient(228.22% 616.67% at 73.71% 435.42%, rgba(255, 255, 255, 0.05) 15.38%, ${brand8Purple} 50.96%, #FFE6B9 100%), ${brand8PurpleDarker}`,
  primaryBtnDisabledFg: `${hexColorWithAlpha(brandWhite, 0.5)}`,
  primaryBtnDisabledBg: `radial-gradient(217.26% 611.25% at 127.54% 430%, ${hexColorWithAlpha(brand8Purple, 0)} 38.46%, ${hexColorWithAlpha(brand8Purple, 0.2)} 69.23%, rgba(255, 230, 185, 0.2) 100%), ${hexColorWithAlpha(brand8Purple, 0.2)}`,
  primaryBtnDisabledBgOpaque: hexColorWithAlpha(brand8Purple, 0.2),
  primaryBtnBoxShadow: '0px 1px 4px rgba(0, 0, 0, 0.1), inset 0px 2px 3px rgba(255, 255, 255, 0.36)',
  primaryBtnContentFilter: `drop-shadow(0px 1px 1px ${brandPurple})`,
  radioButtonBg: brandWhite,
  roundedBtnFontWeight: 400,
  roundedBtnBorderRadius: '10px',
  roundedBtnMediumHeight: '40px',
  roundedBtnMediumPadding: '12px 12px',
  roundedBtnSmallPadding: '6px 10px',
  roundedBtnSmallBorderRadius: '8px',
  roundedBtnTinyPadding: '4px 8px',
  roundedBtnTinyBorderRadius: '6px',
  secondaryBtnBorder: 'none',
  secondaryBtnDisabledBorder: 'none',
  secondaryBtnBg: `${hexColorWithAlpha(brand8Black, 0.75)}`,
  secondaryBtnColor: brandWhite,
  secondaryBtnHoverBg: `${hexColorWithAlpha(brand8Black, 0.70)}`,
  secondaryBtnDisabledFg: `${hexColorWithAlpha(brandWhite, 0.2)}`,
  secondaryBtnBoxShadow: `inset 0px 1px 2px ${hexColorWithAlpha(brandWhite, 0.25)}`,
  secondaryBtnContentFilter: 'drop-shadow(0px 0px 2px rgba(0, 0, 0, 0.75))',
  sfcBackgroundDefault: hexColorWithAlpha(brand8Black, 0.02),
  sfcBackgroundFocus: hexColorWithAlpha(brand8Black, 0.05),
  sfcBackgroundError: hexColorWithAlpha(brand8Black, 0.02),
  sfcBorderDefault: hexColorWithAlpha(brand8Black, 0.05),
  sfcDisabledBackground: hexColorWithAlpha(brand8Black, 0.05),
  sfcDisabledColor: hexColorWithAlpha(brandWhite, 0.5),
  sfcBackdropFilter: 'blur(20px)',
  sfcBorderRadius: '8px',
  sfcDropdownChevronColor: brand8Black,
  sfcDropdownChevronSize: '5px',
  standardRadioButtonIndicatorBackground: hexColorWithAlpha(brand8Black, 0.02),
  standardRadioButtonIndicatorBorder: `1px solid ${hexColorWithAlpha(brand8Black, 0.2)}`,
  standardRadioButtonIndicatorBorderChecked: `1px solid ${hexColorWithAlpha(brand8Black, 0.2)}`,
  standardRadioButtonPseudoElementDisplay: 'block',
  stfDisplay: 'flex',
  stfErrorTextMargin: '0.25em',
  stfFlexDirection: 'column',
  stfGap: '0.5em',
  standardLabelColor: hexColorWithAlpha(brand8Black, 0.5),
  tableBorder: `1px solid ${brand8Gray2}`,
  tableHeadBg: hexColorWithAlpha(brand8Black, 0.02),
  tableHeadFg: hexColorWithAlpha(brand8Black, 0.5),
  placeholderBackgroundColor: brandWhite,
  placeholderBackgroundImage: `linear-gradient(to right, ${hexColorWithAlpha(brand8Black, 0.08)} 0, ${hexColorWithAlpha(brand8Black, 0.15)} 15%, ${hexColorWithAlpha(brand8Black, 0.08)} 30%)`,
  fgBlog: hexColorWithAlpha(brandBlack, 0.75),
  bgBlog: hexColorWithAlpha(brandBlack, 0.2),
  blogBoxShadow: `inset 0px 1px 2px ${hexColorWithAlpha(brandWhite, 0.25)}`,
  blogHighlightBg: brand8Purple,
  blogSubtleBg: hexColorWithAlpha(brandBlack, 0.75),
  appCardHeaderFontFamily: brand8MonospaceFontFamily,
  appCardCondensedWidth: '100%',
  appCardBorder: 'none',
  appCardDisabledBorder: `1px solid ${gray1}`,
  appCardShadowColor: cardShadowColor,
  appCardBgColor: brandWhite,
  badgeBorderRadius: '4px',
  badgeSolidFg: brandWhite,
  badgePurpleColor: brand8Purple,
  badgePurpleOutlinedColor: brand8PurpleDark,
  badgePurplePastelFgColor: brand8PurpleDark,
  badgePurplePastelBgColor: hexColorWithAlpha(brand8Purple, 0.33),
  badgeBlueColor: darkBlueberry,
  badgeBluePastelFgColor: darkBlueberry,
  badgeBluePastelBgColor: hexColorWithAlpha(blueberry, 0.33),
  badgeMangoColor: mango,
  badgeMangoOutlinedColor: darkOrange,
  badgeMangoSolidFgColor: brand8Black,
  badgeMangoPastelFgColor: darkOrange,
  badgeMangoPastelBgColor: hexColorWithAlpha(mango, 0.33),
  badgeMintColor: darkMint,
  badgeMintOutlinedColor: darkMint,
  badgeMintPastelFgColor: darkMint,
  badgeMintPastelBgColor: hexColorWithAlpha(mint, 0.33),
  badgeCherryColor: cherryLight,
  badgeCherryOutlinedColor: cherry,
  badgeCherryPastelFgColor: cherry,
  badgeCherryPastelBgColor: hexColorWithAlpha(cherry, 0.25),
  badgeGrayColor: hexColorWithAlpha(brand8Black, 0.3),
  badgeGraySolidFgColor: hexColorWithAlpha(brand8Black, 0.5),
  badgeGrayOutlinedColor: hexColorWithAlpha(brand8Black, 0.5),
  badgeGrayPastelFgColor: hexColorWithAlpha(brand8Black, 0.5),
  badgeGrayPastelBgColor: hexColorWithAlpha(brand8Black, 0.15),
  recaptchaTheme: 'light',
  navLogoColor: 'purple',
  footerHeaderColor: hexColorWithAlpha(brand8Black, 0.3),
  // TODO(alvin): Overwrite theme attributes with new ones.
}
/* eslint-enable max-len, local-rules/hardcoded-copy */

type UiThemeMode = 'light' | 'dark' | 'brand8dark' | 'brand8light'

const MODE_TO_THEME_MAP: Record<UiThemeMode, UiTheme> = {
  dark: DarkTheme,
  light: LightTheme,
  brand8dark: Brand8DarkTheme,
  brand8light: Brand8LightTheme,
}

const normalizeMode = (mode: UiThemeMode): UiThemeMode => {
  if (BuildIf.ALWAYS_BRAND8_20251009) {
    switch (mode) {
      case 'light':
        return 'brand8light'
      case 'dark':
        return 'brand8dark'
      default:
    }
  }
  return mode
}

interface IUiThemeProvider {
  mode: UiThemeMode
  skipNormalize?: boolean  // Allow the storybook preview to show non-brand8 themes
  children?: React.ReactNode
}

const UiThemeProvider: React.FC<IUiThemeProvider> = ({
  children,
  skipNormalize,
  mode,
}) => {
  const {modeOverride} = useBrand8QaContext()
  const updatedMode = skipNormalize ? mode : normalizeMode(mode)
  const theme = MODE_TO_THEME_MAP[modeOverride ?? updatedMode]
  return (
    <ThemeProvider theme={theme}>
      {children}
    </ThemeProvider>
  )
}

export {
  createThemedStyles,
  useUiTheme,
  UiThemeProvider,
}

export type {
  UiTheme,
  UiThemeMode,
}
