package(default_visibility = ["//visibility:public"])

filegroup(
    name = "frame0",
    srcs = [
        "frame_0.jpg",
        "frame_0_portrait.jpg",
    ],
)

filegroup(
    name = "test-input-landscape",
    srcs = [
        "test-input-landscape.png",
    ],
)

filegroup(
    name = "test-input-portrait",
    srcs = [
        "test-input-portrait.png",
    ],
)

filegroup(
    name = "input-sky-landscape",
    srcs = [
        "input-sky-landscape.png",
    ],
)

filegroup(
    name = "input-sky-portrait",
    srcs = [
        "input-sky-portrait.png",
    ],
)
