const SERVE_COMMAND = 'npx 8w-build --serve'

const MILLISECONDS_PER_SECOND = 1000
const MILLISECONDS_PER_MINUTE = 60 * MILLISECONDS_PER_SECOND
const DEV_SERVER_POLLING_INTERVAL = 2 * MILLISECONDS_PER_SECOND
const DEV_SERVER_POLLING_TIMEOUT = 2 * MILLISECONDS_PER_MINUTE

const MEGA = 2 ** 20
const MAX_TEXT_FILE_UPLOAD_IN_BYTES = 2 * MEGA

export {
  DEV_SERVER_POLLING_INTERVAL,
  DEV_SERVER_POLLING_TIMEOUT,
  MAX_TEXT_FILE_UPLOAD_IN_BYTES,
  SERVE_COMMAND,
}
