// This file was autogenerated by generate-xrcc-types.ts
//   npm run refresh-types

// @inliner-off
import type {EmscriptenModule} from '@repo/reality/app/xr/js/src/types/emscripten'

/* eslint-disable import/group-exports, camelcase, max-len */

export type XrccModule = EmscriptenModule & {
  _c8EmAsm_initSemanticsRenderer: () => void
  _c8EmAsm_updateSemanticsCameraEnvironment: (bytes: number, numBytes: number) => void
  _c8EmAsm_updateSemanticsOptions: (bytes: number, numBytes: number) => void
  _c8EmAsm_semanticsControllerCleanup: () => void
  _c8EmAsm_semanticsControllerRecenter: () => void
  _c8EmAsm_semanticsControllerRenderToCubemap: (bytes: number, numBytes: number) => void
  _c8EmAsm_stageLayersControllerFrame: (bytes: number, numBytes: number) => void
  _c8EmAsm_processStagedLayersControllerFrame: (outputSemanticsTexId: number, outputSemanticsTextW: number, outputSemanticsTexH: number) => void
  _c8EmAsm_initDevice: () => void
  _c8EmAsm_getDeviceModelInfo: (deviceInfo: number, deviceInfoSize: number) => void
  _c8EmAsm_initCameraRuntime: (captureWidth: number, captureHeight: number, displayWidth: number, displayHeight: number, isWebGl2: boolean) => void
  _c8EmAsm_logSummary: () => void
  _c8EmAsm_getReadyInPipeline: (captureWidth: number, captureHeight: number) => void
  _c8EmAsm_markTextureFilledInPipeline: () => void
  _c8EmAsm_markStageFinishedInPipeline: () => void
  _c8EmAsm_releaseInPipeline: (textureId: number) => void
  _c8EmAsm_pushTrace: (tag: number) => void
  _c8EmAsm_popTrace: () => void
  _c8EmAsm_flushTrace: () => void
  _c8EmAsm_setCheckAllZeroes: (checkAllZeroes: boolean) => void
  _c8EmAsm_resetOnPipelineStop: () => void
}
