// This file was autogenerated by generate-xrchunk-types
//   npm run refresh-types

// @inliner-off
import type {EmscriptenModule} from '@repo/reality/app/xr/js/src/types/emscripten'

/* eslint-disable import/group-exports, camelcase, max-len */

export type XrFaceccModule = EmscriptenModule & {
  _c8EmAsm_updateCameraEnvironment: (bytes: number, numBytes: number) => void
  _c8EmAsm_updateFaceOptions: (bytes: number, numBytes: number) => void
  _c8EmAsm_loadFaceDetectModel: (model: number, modelSize: number) => void
  _c8EmAsm_loadFaceMeshModel: (model: number, modelSize: number) => void
  _c8EmAsm_loadEarModel: (model: number, modelSize: number) => void
  _c8EmAsm_faceControllerCleanup: () => void
  _c8EmAsm_stageFaceControllerFrame: (cameraTexture: number) => void
  _c8EmAsm_processStagedFaceControllerFrame: () => void
  _c8EmAsm_getFrameworkData: () => void
}
