// This file was autogenerated by generate-xrmodule-types.ts
//   npm run refresh-types

// @inliner-off
import type {EmscriptenTexture} from '@repo/reality/app/xr/js/src/types/emscripten'

/* eslint-disable import/group-exports, camelcase, max-len */

declare global {
  interface Window {
    _c8: {
      response?: number
      responseSize?: number
      responseTexture?: EmscriptenTexture
      frameworkResponse?: number
      frameworkResponseSize?: number
      logRecord?: number
      logRecordSize?: number
      isAllZeroes?: number
      wasEverNonZero?: number
      lastProcessedCurvyGeometry?: number
      lastProcessedCurvyGeometrySize?: number
      queryResponse?: number
      queryResponseSize?: number
      reality?: number
      realitySize?: number
      realityTexture?: EmscriptenTexture
      version?: string
      hasFetch?: number
      deviceModel?: string
      focalLength?: number
      performanceIndex?: number
      displayWidth?: number
      displayHeight?: number
      useWebGl2?: number
      readyTexture?: EmscriptenTexture
      checkAllZeroes?: number
    }
  }
}
