// This file was autogenerated by generate-xrchunk-types
//   npm run refresh-types

// @inliner-off
import type {EmscriptenModule} from '@repo/reality/app/xr/js/src/types/emscripten'

/* eslint-disable import/group-exports, camelcase, max-len */

export type XrTrackingccModule = EmscriptenModule & {
  _c8EmAsm_addNewDetectionImageLoader: (bytes: number, numBytes: number) => void
  _c8EmAsm_cancelProcessNewDetectionImageTexture: () => void
  _c8EmAsm_processNewDetectionImageTexture: () => void
  _c8EmAsm_unloadDetectionImages: (bytes: number, numBytes: number) => void
  _c8EmAsm_configureXr: (config: number, configSize: number) => void
  _c8EmAsm_clearDetectionImages: () => void
  _c8EmAsm_engineCleanup: () => void
  _c8EmAsm_setDisablePixelBuffer: (disablePixelBuffer: boolean) => void
  _c8EmAsm_initDeviceInfo: (deviceInfo: number, deviceInfoSize: number) => void
  _c8EmAsm_engineInit: (captureWidth: number, captureHeight: number, rotation: number) => void
  _c8EmAsm_setCheckAllZeroes: (checkAllZeroes: number) => void
  _c8EmAsm_query: (ptr: number, size: number) => void
  _c8EmAsm_recenter: () => void
  _c8EmAsm_setEventQueue: (ptr: number, size: number) => void
  _c8EmAsm_stageFrame: (cameraTexture: number, captureWidth: number, captureHeight: number, rotation: number, alpha: number, beta: number, gamma: number, qw: number, qx: number, qy: number, qz: number, videoTimeSeconds: number, frameTimeSeconds: number, timeNanos: number, latitude: number, longitude: number, accuracy: number) => void
  _c8EmAsm_engineOrientationChange: (captureWidth: number, captureHeight: number, rotation: number) => void
  _c8EmAsm_engineVideoSizeChange: (captureWidth: number, captureHeight: number, rotation: number) => void
  _c8EmAsm_setNewMeshesFromJs: (nodeId: number, points: number, pointsLength: number, colors: number, colorsLength: number, triangles: number, trianglesLength: number) => void
  _c8EmAsm_processStagedFrame: () => void
  _c8EmAsm_setXrSessionToken: (xrSessionToken: number) => void
  _c8EmAsm_prepareYuvBuffer: (rows: number, cols: number, bytesPerRow: number, pixels: number) => void
  _c8EmAsm_setCompressedFormat: (encoding: number) => void
  _c8EmAsm_setIsDataRecording: (isDataRecording: boolean) => void
  _c8EmAsm_setEnableDataRecorder: (enableDataRecorder: boolean) => void
}
