config_setting(
    name = "amazonlinux",
    values = {"cpu": "amazonlinux"},
    visibility = ["//visibility:public"],
)

# Info at https://<REMOVED_BEFORE_OPEN_SOURCING>.atlassian.net/l/cp/X9twrGak
config_setting(
    name = "v1-linux",
    values = {"cpu": "v1-linux"},
    visibility = ["//visibility:public"],
)

# Info at https://<REMOVED_BEFORE_OPEN_SOURCING>.atlassian.net/l/cp/GfmbLe0S
config_setting(
    name = "v2-linux",
    values = {"cpu": "v2-linux"},
    visibility = ["//visibility:public"],
)
