load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")

XcodeProjectInfo = provider(
    "Pass information about dependent files in an xcode project.",
    fields = {
        "files": "path to the cmake config file(s).",
        "project_dir": "path to the xcode project directory.",
        "xcodeproj": "symlink to xcodeproj directory",
    },
)

def _project_impl(ctx):
    project_name = ctx.file.project.basename
    xcodeproj_name = ctx.file.xcodeproj.basename

    project_dir = "{name}_xcodeproject".format(name = ctx.label.name)
    project_path = "{project_dir}/{project}".format(project_dir = project_dir, project = project_name)
    xcodeproj_path = "{project_dir}/{xcodeproj}".format(project_dir = project_dir, xcodeproj = xcodeproj_name)

    # List of inputs to xcodebuild.
    xcode_srcs = []

    # Symlink the project directory.
    project_symlink = ctx.actions.declare_file(project_path)
    ctx.actions.symlink(output = project_symlink, target_file = ctx.file.project)
    xcode_srcs.append(project_symlink)

    # Symlink the xcodeproj directory.
    xcodeproj_symlink = ctx.actions.declare_file(xcodeproj_path)
    ctx.actions.symlink(output = xcodeproj_symlink, target_file = ctx.file.xcodeproj)
    xcode_srcs.append(xcodeproj_symlink)

    framework_name = "%sDeps" % project_name
    framework_path = "{}/Frameworks/{}.framework".format(project_dir, framework_name)

    # Create a framework from containing the native library dependencies.
    if ctx.attr.plugin_src and ctx.attr.plugin_src[DefaultInfo]:
        plugin_src_files = ctx.attr.plugin_src[DefaultInfo].files.to_list()
        if len(plugin_src_files) != 1:
            fail("Expected only one DefaultInfo provider in plugin_src")

        # Create the Info.plist.
        info_out = ctx.actions.declare_file("{}/Info.plist".format(framework_path))
        xcode_srcs.append(info_out)

        ctx.actions.write(
            info_out,
            '<?xml version="1.0" encoding="UTF-8"?>\n' +
            '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n' +
            '<plist version="1.0">\n' +
            "<dict>\n" +
            "    <key>CFBundleExecutable</key>\n" +
            "    <string>%s</string>\n" % framework_name +
            "    <key>CFBundleIdentifier</key>\n" +
            "    <string>com.niantic.framework</string>\n" +
            "    <key>CFBundleShortVersionString</key>\n" +
            "    <string>1.0</string>\n" +
            "    <key>CFBundleVersion</key>\n" +
            "    <string>1.0.0</string>\n" +
            "    <key>MinimumOSVersion</key>\n" +
            "    <string>%s</string>\n" % ctx.attr._min_ios_version[BuildSettingInfo].value +
            "</dict>\n" +
            "</plist>\n",
        )

        dynamic_library = ctx.actions.declare_file("{}/{}".format(framework_path, framework_name))

        # Copy and rename the dynamic library, then update its rpaths for each linked library.
        dylib_path = "@rpath/%s.framework/%s" % (framework_name, framework_name)

        install_name_changes = "-id " + dylib_path
        ctx.actions.run_shell(
            inputs = plugin_src_files,
            outputs = [dynamic_library],
            tools = [ctx.file._install_name_tool],
            env = {
                "RUNFILES_DIR": "{}.runfiles".format(ctx.file._install_name_tool.path),
                "INSTALL_NAME_TOOL": "{int_full}.runfiles/{workspace}/{int_short}".format(int_full = ctx.file._install_name_tool.path, workspace = ctx.workspace_name, int_short = ctx.file._install_name_tool.short_path),
            },
            command = "cp {src} {dst} && chmod u+w {dst} && $INSTALL_NAME_TOOL {changes} {dst} && chmod u-w {dst}".format(
                src = plugin_src_files[0].path,
                dst = dynamic_library.path,
                changes = install_name_changes,
            ),
        )
        xcode_srcs.append(dynamic_library)

        # Copy all transitive header files into the framework
        all_dep_headers = depset(transitive = [dep[CcInfo].compilation_context.headers for dep in ctx.attr.deps])

        for hdr in all_dep_headers.to_list():
            hdr_path = "{}/Headers/{}".format(framework_path, hdr.short_path)
            hdr_copy = ctx.actions.declare_file(hdr_path)

            # XCode fails when installing iOS apps if the header files are
            # symlinks, so we copy them into the project instead.
            ctx.actions.run_shell(
                inputs = [hdr],
                outputs = [hdr_copy],
                command = "cp {} {}".format(hdr.path, hdr_copy.path),
            )
            xcode_srcs.append(hdr_copy)

    # Create wrapper script to open xcode editor.
    wrapper_content = [
        "#!/bin/bash --norc",
        "# Generated by xcode_project.bzl",
        "set -eu",
        "DIR=`dirname ${BASH_SOURCE[0]}`\n" +
        "# Quit XCode, since it won't reopen the project otherwise.",
        "osascript -e 'quit app \"XCode\"'",
        "# Incantation to open a symlink XCode project and keep symlink path.",
        "open -a Xcode --args \"${PWD}/${DIR}/%s\"" % project_dir,
        "",
    ]

    ctx.actions.write(
        output = ctx.outputs.executable,
        content = "\n".join(wrapper_content),
        is_executable = True,
    )
    outputs = [ctx.outputs.executable]

    return [
        DefaultInfo(
            files = depset(outputs + xcode_srcs),
        ),
        OutputGroupInfo(
            project_files = xcode_srcs,
        ),
        cc_common.merge_cc_infos(cc_infos = [dep[CcInfo] for dep in ctx.attr.deps]),
        XcodeProjectInfo(
            files = depset(xcode_srcs),
            project_dir = project_dir,
            xcodeproj = xcodeproj_symlink,
        ),
    ]

_xcode_project = rule(
    implementation = _project_impl,
    attrs = {
        "deps": attr.label_list(
            providers = [CcInfo],
        ),
        "plugin_src": attr.label(),
        "_install_name_tool": attr.label(
            default = "//bzl/llvm:llvm-install-name-tool",
            allow_single_file = True,
            executable = True,
            cfg = "host",
        ),
        "xcodeproj": attr.label(
            mandatory = True,
            allow_single_file = True,
        ),
        "project": attr.label(
            mandatory = True,
            allow_single_file = True,
        ),
        "srcs": attr.label_list(
            allow_files = True,
        ),
        "_min_ios_version": attr.label(
            providers = [BuildSettingInfo],
            default = "//bzl/xcode:ios-min-version",
        ),
    },
    executable = True,
)

def xcode_project(name, project, deps = [], target_compatible_with = None):
    """Bazel rule to build an XCode project by symlinking files from the source repository.

    Args:
      name (string): Target name and relative path to the XCode project directory.
      project (Label): Pretty name for the XCode project, e.g., MyAppFun.
      deps (List[Label]): CC Libraries that should be linked into a Native Plugin.
    """

    plugin_target = None
    if deps:
        plugin_target = "%s-deps" % name

        native.cc_binary(
            name = plugin_target,
            deps = deps,
            linkshared = True,
            linkopts = [
                "-all_load",  # Load all symbols linked in deps.
                "-fembed-bitcode",
                "-lc++",  # Link in libc++.
            ],
        )

    xcodeproj = project + ".xcodeproj"

    # These are the actual sources, used in dependent rules that need to rebuild
    # if a source is modified.
    sources = native.glob(
        include = [
            project + "/**",
            xcodeproj + "/**",
        ],
        exclude = [
            ".*",
            "**/.*",
        ],
    )

    _xcode_project(
        deps = deps,
        name = name,
        plugin_src = plugin_target,
        srcs = sources,
        xcodeproj = xcodeproj,
        project = project,
        exec_compatible_with = [
            "@platforms//os:osx",
        ],
        target_compatible_with = target_compatible_with if target_compatible_with != None else select({
            "@the8thwall//bzl/conditions:apple": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }),
    )
