#!/bin/bash --norc

export RUNFILES_DIR=${RUNFILES_DIR:-$0.runfiles}

# Add the toolchain env vars.
WORKSPACE="{{WORKSPACE}}"
WORKSPACE_ENV="{{WORKSPACE_ENV}}"
RELATIVE_EXTERNAL_TOOLCHAINS_DIR="{{RELATIVE_EXTERNAL_TOOLCHAINS_DIR}}"
XCTOOLCHAIN="{{XCTOOLCHAIN}}"

# Source BAZEL_OUTPUT_BASE.
. ${RUNFILES_DIR}/${WORKSPACE}/${WORKSPACE_ENV}

$BAZEL_OUTPUT_BASE/$RELATIVE_EXTERNAL_TOOLCHAINS_DIR/$XCTOOLCHAIN/usr/bin/dsymutil "$@" 2> >(sed -e "/timestamp mismatch/D")
