"""
This file is used to generate the Rust toolchains. We do this so that we can use a rustc wrapper
which provides the correct SDKROOT.

You can build one of the variants directly with, for example:
- "bazel build @rust_toolchains//:toolchain-exec-aarch64-apple-darwin-target-aarch64-apple-ios"

This rule is based on the toolchains which are automatically generated by rules_rust, i.e. we
reproduce the same outputs. You can inspect them by commenting out rust_register_all_toolchains() in
WORKSPACE and setting `register_toolchains = True,` in rust_register_toolchains().
"""

VARIANTS = [
    {
        "name": "ios",
        "platform": "iPhoneOS",
        "exec_triple": "aarch64-apple-darwin",
        "target_triple": "aarch64-apple-ios",
        "tool_prefix": "@rust_darwin_aarch64__aarch64-apple-ios__stable_tools//",
    },
    {
        "name": "osx",
        "platform": "MacOSX",
        "exec_triple": "aarch64-apple-darwin",
        "target_triple": "aarch64-apple-darwin",
        "tool_prefix": "@rust_darwin_aarch64__aarch64-apple-darwin__stable_tools//",
    },
    {
        "name": "android",
        "platform": "Android",
        "exec_triple": "aarch64-apple-darwin",
        "target_triple": "aarch64-linux-android",
        "tool_prefix": "@rust_darwin_aarch64__aarch64-linux-android__stable_tools//",
    },
]

def _toolchain_name(exec_triple, target_triple):
    return "rust-toolchain-exec-{exec_triple}-target-{target_triple}".format(exec_triple = exec_triple, target_triple = target_triple)

def _rust_toolchains_impl(repository_ctx):
    build_content = [
        'load("@rules_rust//rust:toolchain.bzl", "rust_toolchain")',
        'load("@//bzl/crosstool:rustc.bzl", "rustc")',
    ]
    for v in VARIANTS:
        rustc_wrapper_name = "rustc-wrapper-{name}".format(name = v["name"])
        toolchain_name = _toolchain_name(v["exec_triple"], v["target_triple"])
        internal_toolchain_name = "{toolchain_name}-internal".format(toolchain_name = toolchain_name)
        if v["platform"] == "iPhoneOS":
            stdlib_linkflags = [
                "-lSystem",
                "-lobjc",
                "-Wl,-framework,Security",
                "-Wl,-framework,Foundation",
                "-lresolv",
            ]
            dylib_ext = ".dylib"
        elif v["platform"] == "MacOSX":
            stdlib_linkflags = [
                "-lSystem",
                "-lresolv",
            ]
            dylib_ext = ".dylib"
        elif v["platform"] == "Android":
            stdlib_linkflags = [
                "-ldl",
                "-llog",
            ]
            dylib_ext = ".so"
        else:
            stdlib_linkflags = []
            dylib_ext = ".so"

        build_content.append("""
rustc(
    name = "{rustc_wrapper_name}",
    src = "@//bzl/crosstool:rustc-wrapper.sh",
    platform = "{platform}",
    rustc = "{tool_prefix}:rustc",
)""".format(
            rustc_wrapper_name = rustc_wrapper_name,
            platform = v["platform"],
            tool_prefix = v["tool_prefix"],
        ))

        build_content.append("""
rust_toolchain(
    name = "{internal_toolchain_name}",
    allocator_library = "@rules_rust//ffi/cc/allocator_library",
    binary_ext = "",
    cargo = "{tool_prefix}:cargo",
    cargo_clippy = "{tool_prefix}:cargo_clippy_bin",
    clippy_driver = "{tool_prefix}:clippy_driver_bin",
    # TODO(paris): Use a common version from WORKSPACE.
    default_edition = "2021",
    dylib_ext = "{dylib_ext}",
    exec_triple = "{exec_triple}",
    extra_exec_rustc_flags = [],
    extra_rustc_flags = [],
    global_allocator_library = "@rules_rust//ffi/cc/global_allocator_library",
    llvm_cov = "{tool_prefix}:llvm_cov_bin",
    llvm_profdata = "{tool_prefix}:llvm_profdata_bin",
    opt_level = None,
    rust_doc = "{tool_prefix}:rustdoc",
    rust_std = "{tool_prefix}:rust_std-{target_triple}",
    rustc = ":{rustc_wrapper_name}",
    rustc_lib = "{tool_prefix}:rustc_lib",
    rustfmt = "{tool_prefix}:rustfmt_bin",
    staticlib_ext = ".a",
    stdlib_linkflags = {stdlib_linkflags},
    # TODO(paris): Use a common version from WORKSPACE.
    tags = ["rust_version=1.82.0"],
    target_triple = "{target_triple}",
    visibility = ["//visibility:public"],
)""".format(
            internal_toolchain_name = internal_toolchain_name,
            tool_prefix = v["tool_prefix"],
            exec_triple = v["exec_triple"],
            target_triple = v["target_triple"],
            rustc_wrapper_name = rustc_wrapper_name,
            dylib_ext = dylib_ext,
            stdlib_linkflags = stdlib_linkflags,
        ))

        build_content.append("""
toolchain(
    name = "{toolchain_name}",
    exec_compatible_with = [
        "@platforms//cpu:aarch64",
        "@platforms//os:osx",
    ],
    target_compatible_with = ["@platforms//os:{name}"],
    target_settings = ["@rules_rust//rust/toolchain/channel:stable"],
    toolchain = ":{internal_toolchain_name}",
    toolchain_type = "@rules_rust//rust:toolchain",
)""".format(
            toolchain_name = toolchain_name,
            internal_toolchain_name = internal_toolchain_name,
            name = v["name"],
        ))

    repository_ctx.file("BUILD", content = "\n\n".join(build_content), executable = False)

rust_toolchains = repository_rule(
    implementation = _rust_toolchains_impl,
    attrs = {},
)

def rust_register_all_toolchains(name):
    """
    Register the generated toolchains.

    Args:
        name: The toolchain name.
    """

    # First generate the toolchains in a BUILD file.
    rust_toolchains(name = name)

    # Then register them.
    toolchain_names = []
    for v in VARIANTS:
        toolchain_names.append(
            "@{name}//:{toolchain_name}".format(
                name = name,
                toolchain_name = _toolchain_name(v["exec_triple"], v["target_triple"]),
            ),
        )

    # NOTE(christoph): This is registered after the other toolchains to catch unsupported platforms.
    # To fix, either add a extra_target_triples to support that platform,
    # or target_compatible_with on the target.
    toolchain_names.append(
        "//bzl/crosstool:empty-rust-toolchain",
    )

    # Register rust_analyzer toolchain (needed for rust-analyzer support)
    toolchain_names.append(
        "@rust_analyzer_1.82.0//:toolchain",
    )

    native.register_toolchains(*toolchain_names)
