import {v4 as uuid} from 'uuid'

const IMAGE_TARGET_MAX_WIDTH = 2000
const IMAGE_TARGET_MAX_HEIGHT = 2000
const IMAGE_TARGET_PAGE_LINK = 'https://www.8thwall.com/docs/guides/image-targets/'
const OFFLINE_IMAGE_TARGET_PAGE_LINK = 'https://8th.io/image-targets-update'

const IMAGE_TARGET_EDITOR_GALLERY_ID = uuid()
const IMAGE_TARGET_BROWSER_GALLERY_ID = uuid()
const IMAGE_TARGET_ENTITY_GALLERY_ID = uuid()
const IMAGE_TARGET_SIMULATOR_PANEL_GALLERY_ID = uuid()
const IMAGE_TARGET_SIMULATOR_GALLERY_ID = uuid()
const IMAGE_TARGET_STUDIO_USE_GALLERY_ID = uuid()

export {
  IMAGE_TARGET_MAX_WIDTH,
  IMAGE_TARGET_MAX_HEIGHT,
  IMAGE_TARGET_PAGE_LINK,
  IMAGE_TARGET_EDITOR_GALLERY_ID,
  IMAGE_TARGET_BROWSER_GALLERY_ID,
  IMAGE_TARGET_ENTITY_GALLERY_ID,
  IMAGE_TARGET_SIMULATOR_PANEL_GALLERY_ID,
  IMAGE_TARGET_SIMULATOR_GALLERY_ID,
  IMAGE_TARGET_STUDIO_USE_GALLERY_ID,
  OFFLINE_IMAGE_TARGET_PAGE_LINK,
}
