package(default_visibility = [
    "//visibility:public",
])

filegroup(
    name = "textures",
    testonly = 1,
    srcs = [
        "8w_customer_face.png",
        "cubemaps_skybox.png",
    ],
)

filegroup(
    name = "doty-glb",
    testonly = 1,
    srcs = [
        "doty.glb",
    ],
)
