load("//bzl/js:js.bzl", "js_library")

package(
    default_visibility = ["//visibility:public"],
)

js_library(
    name = "TextAlign",
    srcs = [
        "TextAlign.ts",
    ],
    deps = [
        "//c8/ecs/src/8mesh/utils/inline-layout:inline-types",
    ],
)

js_library(
    name = "Whitespace",
    srcs = [
        "Whitespace.ts",
    ],
    deps = [
        "//c8/ecs/src/8mesh/utils/inline-layout:inline-types",
    ],
)

js_library(
    name = "inline-types",
    srcs = [
        "inline-types.ts",
    ],
)
