filegroup(
    name = "reference-media",
    testonly = 1,
    srcs = [
        "big-buck-bunny.webm",
        "reference-0.mkv",
        "reference-0.mp4",
        "reference-vp8-vorbis.webm",
        "reference-vp9-opus.webm",
    ],
    visibility = ["//visibility:public"],
)
