filegroup(
    name = "info-plist-framework-template",
    srcs = ["Info.plist.framework.tpl"],
    visibility = ["//bzl/apple:__subpackages__"],
)

filegroup(
    name = "build-apple-framework",
    srcs = ["build-apple-framework.sh"],
    visibility = ["//bzl/apple:__subpackages__"],
)
