/* eslint-disable */
// Generated by xrhome/tools/generate-studio-schema.ts
import { DeepReadonly } from 'ts-essentials'
import type {StudioComponentData} from '@ecs/shared/studio-component'

const BUILTIN_COMPONENT_SCHEMA = [
  {
    "name": "position-animation",
    "schema": {
      "autoFrom": "boolean",
      "fromX": "f32",
      "fromY": "f32",
      "fromZ": "f32",
      "toX": "f32",
      "toY": "f32",
      "toZ": "f32",
      "duration": "f32",
      "loop": "boolean",
      "reverse": "boolean",
      "easeIn": "boolean",
      "easeOut": "boolean",
      "easingFunction": "string",
      "target": "eid"
    },
    "schemaDefaults": {
      "duration": 1000,
      "loop": true
    },
    "schemaPresentation": {
      "fields": {
        "fromX": {
          "group": "from"
        },
        "fromY": {
          "group": "from"
        },
        "fromZ": {
          "group": "from"
        },
        "toX": {
          "group": "to"
        },
        "toY": {
          "group": "to"
        },
        "toZ": {
          "group": "to"
        },
        "reverse": {
          "condition": "loop=true"
        },
        "easingFunction": {
          "mode": "enum",
          "enumValues": [
            "Quadratic",
            "Cubic",
            "Quartic",
            "Quintic",
            "Sinusoidal",
            "Exponential",
            "Circular",
            "Elastic",
            "Back",
            "Bounce"
          ],
          "condition": "easeIn=true|easeOut=true"
        },
        "target": {
          "label": "Target (optional)"
        }
      },
      "groups": {
        "from": {
          "type": "vector3",
          "condition": "autoFrom=false"
        },
        "to": {
          "type": "vector3"
        }
      },
      "sections": {}
    }
  },
  {
    "name": "scale-animation",
    "schema": {
      "autoFrom": "boolean",
      "fromX": "f32",
      "fromY": "f32",
      "fromZ": "f32",
      "toX": "f32",
      "toY": "f32",
      "toZ": "f32",
      "duration": "f32",
      "loop": "boolean",
      "reverse": "boolean",
      "easeIn": "boolean",
      "easeOut": "boolean",
      "easingFunction": "string",
      "target": "eid"
    },
    "schemaDefaults": {
      "duration": 1000,
      "loop": true
    },
    "schemaPresentation": {
      "fields": {
        "fromX": {
          "group": "from"
        },
        "fromY": {
          "group": "from"
        },
        "fromZ": {
          "group": "from"
        },
        "toX": {
          "group": "to"
        },
        "toY": {
          "group": "to"
        },
        "toZ": {
          "group": "to"
        },
        "reverse": {
          "condition": "loop=true"
        },
        "easingFunction": {
          "mode": "enum",
          "enumValues": [
            "Quadratic",
            "Cubic",
            "Quartic",
            "Quintic",
            "Sinusoidal",
            "Exponential",
            "Circular",
            "Elastic",
            "Back",
            "Bounce"
          ],
          "condition": "easeIn=true|easeOut=true"
        },
        "target": {
          "label": "Target (optional)"
        }
      },
      "groups": {
        "from": {
          "type": "vector3",
          "condition": "autoFrom=false"
        },
        "to": {
          "type": "vector3"
        }
      },
      "sections": {}
    }
  },
  {
    "name": "rotate-animation",
    "schema": {
      "autoFrom": "boolean",
      "fromX": "f32",
      "fromY": "f32",
      "fromZ": "f32",
      "toX": "f32",
      "toY": "f32",
      "toZ": "f32",
      "shortestPath": "boolean",
      "duration": "f32",
      "loop": "boolean",
      "reverse": "boolean",
      "easeIn": "boolean",
      "easeOut": "boolean",
      "easingFunction": "string",
      "target": "eid"
    },
    "schemaDefaults": {
      "shortestPath": true,
      "duration": 1000,
      "loop": true
    },
    "schemaPresentation": {
      "fields": {
        "fromX": {
          "group": "from"
        },
        "fromY": {
          "group": "from"
        },
        "fromZ": {
          "group": "from"
        },
        "toX": {
          "group": "to"
        },
        "toY": {
          "group": "to"
        },
        "toZ": {
          "group": "to"
        },
        "reverse": {
          "condition": "loop=true"
        },
        "easingFunction": {
          "mode": "enum",
          "enumValues": [
            "Quadratic",
            "Cubic",
            "Quartic",
            "Quintic",
            "Sinusoidal",
            "Exponential",
            "Circular",
            "Elastic",
            "Back",
            "Bounce"
          ],
          "condition": "easeIn=true|easeOut=true"
        },
        "target": {
          "label": "Target (optional)"
        }
      },
      "groups": {
        "from": {
          "type": "vector3",
          "condition": "autoFrom=false"
        },
        "to": {
          "type": "vector3"
        }
      },
      "sections": {}
    }
  },
  {
    "name": "custom-vec3-animation",
    "schema": {
      "attribute": "string",
      "autoFrom": "boolean",
      "fromX": "f32",
      "fromY": "f32",
      "fromZ": "f32",
      "toX": "f32",
      "toY": "f32",
      "toZ": "f32",
      "duration": "f32",
      "loop": "boolean",
      "reverse": "boolean",
      "easeIn": "boolean",
      "easeOut": "boolean",
      "easingFunction": "string",
      "target": "eid"
    },
    "schemaDefaults": {
      "duration": 1000,
      "loop": true
    },
    "schemaPresentation": {
      "fields": {
        "attribute": {
          "mode": "attribute",
          "attribute": "vector3"
        },
        "fromX": {
          "group": "from"
        },
        "fromY": {
          "group": "from"
        },
        "fromZ": {
          "group": "from"
        },
        "toX": {
          "group": "to"
        },
        "toY": {
          "group": "to"
        },
        "toZ": {
          "group": "to"
        },
        "reverse": {
          "condition": "loop=true"
        },
        "easingFunction": {
          "mode": "enum",
          "enumValues": [
            "Quadratic",
            "Cubic",
            "Quartic",
            "Quintic",
            "Sinusoidal",
            "Exponential",
            "Circular",
            "Elastic",
            "Back",
            "Bounce"
          ],
          "condition": "easeIn=true|easeOut=true"
        },
        "target": {
          "label": "Target (optional)"
        }
      },
      "groups": {
        "from": {
          "type": "vector3",
          "condition": "autoFrom=false"
        },
        "to": {
          "type": "vector3"
        }
      },
      "sections": {}
    }
  },
  {
    "name": "custom-property-animation",
    "schema": {
      "attribute": "string",
      "property": "string",
      "autoFrom": "boolean",
      "from": "f32",
      "to": "f32",
      "duration": "f32",
      "loop": "boolean",
      "reverse": "boolean",
      "easeIn": "boolean",
      "easeOut": "boolean",
      "easingFunction": "string",
      "target": "eid"
    },
    "schemaDefaults": {
      "duration": 1000,
      "loop": true
    },
    "schemaPresentation": {
      "fields": {
        "attribute": {
          "mode": "attribute",
          "attribute": "number"
        },
        "property": {
          "mode": "property",
          "propertyOf": "attribute"
        },
        "from": {
          "condition": "autoFrom=false"
        },
        "reverse": {
          "condition": "loop=true"
        },
        "easingFunction": {
          "mode": "enum",
          "enumValues": [
            "Quadratic",
            "Cubic",
            "Quartic",
            "Quintic",
            "Sinusoidal",
            "Exponential",
            "Circular",
            "Elastic",
            "Back",
            "Bounce"
          ],
          "condition": "easeIn=true|easeOut=true"
        },
        "target": {
          "label": "Target (optional)"
        }
      },
      "groups": {},
      "sections": {}
    }
  },
  {
    "name": "follow-animation",
    "schema": {
      "target": "eid",
      "minDistance": "f32",
      "maxDistance": "f32",
      "elasticity": "f32"
    },
    "schemaDefaults": {
      "elasticity": 1
    },
    "schemaPresentation": {
      "fields": {},
      "groups": {},
      "sections": {}
    }
  },
  {
    "name": "look-at-animation",
    "schema": {
      "target": "eid",
      "targetX": "f32",
      "targetY": "f32",
      "targetZ": "f32"
    },
    "schemaPresentation": {
      "fields": {
        "targetX": {
          "group": "targetVector"
        },
        "targetY": {
          "group": "targetVector"
        },
        "targetZ": {
          "group": "targetVector"
        }
      },
      "groups": {
        "targetVector": {
          "type": "vector3",
          "condition": "target=null"
        }
      },
      "sections": {}
    }
  },
  {
    "name": "particle-emitter",
    "schema": {
      "stopped": "boolean",
      "emitterLife": "f32",
      "particlesPerShot": "ui32",
      "emitDelay": "f32",
      "minimumLifespan": "f32",
      "maximumLifespan": "f32",
      "mass": "f32",
      "gravity": "f32",
      "scale": "f32",
      "forceX": "f32",
      "forceY": "f32",
      "forceZ": "f32",
      "spread": "f32",
      "radialVelocity": "f32",
      "spawnAreaType": "string",
      "spawnAreaWidth": "f32",
      "spawnAreaHeight": "f32",
      "spawnAreaDepth": "f32",
      "spawnAreaRadius": "f32",
      "boundingZoneType": "string",
      "boundingZoneWidth": "f32",
      "boundingZoneHeight": "f32",
      "boundingZoneDepth": "f32",
      "boundingZoneRadius": "f32",
      "resourceType": "string",
      "resourceUrl": "string",
      "blendingMode": "string",
      "animateColor": "boolean",
      "colorStart": "string",
      "colorEnd": "string",
      "randomDrift": "boolean",
      "randomDriftRange": "f32",
      "collisions": "boolean"
    },
    "schemaDefaults": {
      "emitterLife": 1,
      "particlesPerShot": 1,
      "emitDelay": 1,
      "minimumLifespan": 1,
      "maximumLifespan": 10,
      "mass": 1,
      "scale": 1,
      "spawnAreaType": "point",
      "resourceType": "none"
    },
    "schemaPresentation": {
      "fields": {
        "spawnAreaType": {
          "mode": "enum",
          "enumValues": [
            "point",
            "box",
            "sphere"
          ]
        },
        "spawnAreaWidth": {
          "condition": "spawnAreaType=box"
        },
        "spawnAreaHeight": {
          "condition": "spawnAreaType=box"
        },
        "spawnAreaDepth": {
          "condition": "spawnAreaType=box"
        },
        "spawnAreaRadius": {
          "condition": "spawnAreaType=sphere"
        },
        "boundingZoneType": {
          "mode": "enum",
          "enumValues": [
            "none",
            "box",
            "sphere"
          ]
        },
        "boundingZoneWidth": {
          "condition": "boundingZoneType=box"
        },
        "boundingZoneHeight": {
          "condition": "boundingZoneType=box"
        },
        "boundingZoneDepth": {
          "condition": "boundingZoneType=box"
        },
        "boundingZoneRadius": {
          "condition": "boundingZoneType=sphere"
        },
        "resourceType": {
          "mode": "enum",
          "enumValues": [
            "none",
            "sprite",
            "model"
          ]
        },
        "resourceUrl": {
          "condition": "resourceType=model|resourceType=sprite",
          "mode": "asset"
        },
        "blendingMode": {
          "condition": "resourceType=sprite",
          "mode": "enum",
          "enumValues": [
            "none",
            "normal",
            "add",
            "multiply",
            "subtract"
          ]
        },
        "animateColor": {
          "condition": "resourceType=sprite"
        },
        "colorStart": {
          "condition": "animateColor=true&resourceType=sprite"
        },
        "colorEnd": {
          "condition": "animateColor=true&resourceType=sprite"
        },
        "randomDriftRange": {
          "condition": "randomDrift=true"
        }
      },
      "groups": {},
      "sections": {}
    }
  },
  {
    "name": "orbit-controls",
    "schema": {
      "speed": "f32",
      "maxAngularSpeed": "f32",
      "maxZoomSpeed": "f32",
      "distanceMin": "f32",
      "distanceMax": "f32",
      "pitchAngleMin": "f32",
      "pitchAngleMax": "f32",
      "constrainYaw": "boolean",
      "yawAngleMin": "f32",
      "yawAngleMax": "f32",
      "inertiaFactor": "f32",
      "focusEntity": "eid",
      "invertedX": "boolean",
      "invertedY": "boolean",
      "invertedZoom": "boolean",
      "controllerSupport": "boolean",
      "horizontalSensitivity": "f32",
      "verticalSensitivity": "f32"
    },
    "schemaDefaults": {
      "speed": 5,
      "maxAngularSpeed": 10,
      "maxZoomSpeed": 10,
      "distanceMin": 5,
      "distanceMax": 20,
      "pitchAngleMin": -90,
      "pitchAngleMax": 90,
      "constrainYaw": false,
      "yawAngleMin": 0,
      "yawAngleMax": 0,
      "inertiaFactor": 0.3,
      "horizontalSensitivity": 1,
      "verticalSensitivity": 1
    },
    "schemaPresentation": {
      "fields": {
        "yawAngleMin": {
          "condition": "constrainYaw=true"
        },
        "yawAngleMax": {
          "condition": "constrainYaw=true"
        },
        "horizontalSensitivity": {
          "condition": "controllerSupport=true"
        },
        "verticalSensitivity": {
          "condition": "controllerSupport=true"
        }
      },
      "groups": {},
      "sections": {}
    }
  },
  {
    "name": "face-anchor",
    "schema": {}
  },
  {
    "name": "face-mesh-anchor",
    "schema": {}
  },
  {
    "name": "face-attachment",
    "schema": {
      "point": "string"
    },
    "schemaDefaults": {
      "point": "forehead"
    },
    "schemaPresentation": {
      "fields": {
        "point": {
          "mode": "enum",
          "enumValues": [
            "forehead",
            "rightEyebrowInner",
            "rightEyebrowMiddle",
            "rightEyebrowOuter",
            "leftEyebrowInner",
            "leftEyebrowMiddle",
            "leftEyebrowOuter",
            "leftCheek",
            "rightCheek",
            "noseBridge",
            "noseTip",
            "leftEye",
            "rightEye",
            "leftEyeOuterCorner",
            "rightEyeOuterCorner",
            "upperLip",
            "lowerLip",
            "mouth",
            "mouthRightCorner",
            "mouthLeftCorner",
            "chin",
            "leftIris",
            "rightIris",
            "leftUpperEyelid",
            "rightUpperEyelid",
            "leftLowerEyelid",
            "rightLowerEyelid",
            "leftHelix",
            "leftCanal",
            "leftLobe",
            "rightHelix",
            "rightCanal",
            "rightLobe"
          ]
        }
      },
      "groups": {},
      "sections": {}
    }
  },
  {
    "name": "location-anchor",
    "schema": {}
  },
  {
    "name": "fly-controller",
    "schema": {
      "verticalSensitivity": "f32",
      "horizontalSensitivity": "f32",
      "moveSpeedX": "f32",
      "moveSpeedY": "f32",
      "moveSpeedZ": "f32",
      "invertedY": "boolean",
      "invertedX": "boolean"
    },
    "schemaDefaults": {
      "verticalSensitivity": 1,
      "horizontalSensitivity": 1,
      "moveSpeedX": 1,
      "moveSpeedY": 0.5,
      "moveSpeedZ": 0.5
    },
    "schemaPresentation": {
      "fields": {},
      "groups": {},
      "sections": {}
    }
  }
] as const

export {
  BUILTIN_COMPONENT_SCHEMA,
}
